/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dishcovery;
<<<<<<< HEAD
import java.awt.Insets;
import java.text.SimpleDateFormat;
import javax.swing.JScrollPane;
import javax.swing.JTabbedPane;
import javax.swing.JPanel;
=======
>>>>>>> a8744219926975f3c37f4a6d807cbd64e7020fe1
import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public class ADD extends javax.swing.JFrame {
    private final config.config con = new config.config();
    private String recipeId = null;

    /**
     * Creates new form homePage2
     */
    public ADD() {
        config.Session.requireLogin(this);
<<<<<<< HEAD
        if (!config.Session.getInstance().isLoggedIn()) { return; }
=======
>>>>>>> a8744219926975f3c37f4a6d807cbd64e7020fe1
        initComponents();
    }

    public ADD(String id) {
        config.Session.requireLogin(this);
<<<<<<< HEAD
        if (!config.Session.getInstance().isLoggedIn()) { return; }
=======
>>>>>>> a8744219926975f3c37f4a6d807cbd64e7020fe1
        initComponents();
        this.recipeId = id;
        ADD8.setText("Update");
        jLabel9.setText("Update Recipe");
        populateFields(id);
    }

    

    private void populateFields(String id) {
        String sql = "SELECT * FROM Recipes WHERE r_id = ?";
        try (java.sql.Connection conn = con.connectDB();
             java.sql.PreparedStatement pstmt = conn.prepareStatement(sql)) {
            pstmt.setString(1, id);
            try (java.sql.ResultSet rs = pstmt.executeQuery()) {
                if (rs.next()) {
                    Title1.setText(rs.getString("r_title"));
                    Description.setText(rs.getString("r_description"));
                    Instruction.setText(rs.getString("r_instructions"));
                    String dateStr = rs.getString("r_date");
                    if (dateStr != null && !dateStr.isEmpty()) {
                        try {
                            java.util.Date d = new java.text.SimpleDateFormat("yyyy-MM-dd").parse(dateStr);
                            this.jDateChooser1.setDate(d);
                        } catch (Exception ex) {
                        }
                    }
                    category.setSelectedItem(rs.getString("r_category"));
                    
                                   
                }
            }
        } catch (java.sql.SQLException e) {
            System.out.println("Error populating fields: " + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSpinner1 = new javax.swing.JSpinner();
        jPanel6 = new javax.swing.JPanel();
        jDialog1 = new javax.swing.JDialog();
        choice1 = new java.awt.Choice();
        canvas1 = new java.awt.Canvas();
        jDialog2 = new javax.swing.JDialog();
        jTextField10 = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jPanel18 = new javax.swing.JPanel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jPanel17 = new javax.swing.JPanel();
        jLabel38 = new javax.swing.JLabel();
        ADD7 = new javax.swing.JButton();
        category = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Instruction = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        Description = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        Title1 = new javax.swing.JTextField();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        ADD8 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        jPanel6.setBackground(new java.awt.Color(0, 0, 0,80));

        jTextField10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField10ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 390, -1, -1));

        jPanel2.setLayout(null);

        jPanel12.setBackground(new java.awt.Color(0, 0, 0,50));
        jPanel12.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel12.setLayout(null);

        jPanel18.setBackground(new java.awt.Color(0, 0, 0,80));
        jPanel18.setLayout(null);

        jLabel34.setForeground(new java.awt.Color(255, 255, 255));
        jLabel34.setText("Title:");
        jPanel18.add(jLabel34);
        jLabel34.setBounds(20, 210, 60, 20);

        jLabel35.setForeground(new java.awt.Color(255, 255, 255));
        jLabel35.setText("SELECT");
        jPanel18.add(jLabel35);
        jLabel35.setBounds(160, 180, 70, 20);

        jLabel36.setForeground(new java.awt.Color(255, 255, 255));
        jLabel36.setText("Instruction:");
        jPanel18.add(jLabel36);
        jLabel36.setBounds(320, 200, 70, 20);

        jLabel37.setForeground(new java.awt.Color(255, 255, 255));
        jLabel37.setText("Date:");
        jPanel18.add(jLabel37);
        jLabel37.setBounds(20, 270, 60, 20);

        jPanel17.setBackground(new java.awt.Color(255, 255, 255));
        jPanel18.add(jPanel17);
        jPanel17.setBounds(100, 20, 180, 150);

        jLabel38.setForeground(new java.awt.Color(255, 255, 255));
        jLabel38.setText("Category:");
        jPanel18.add(jLabel38);
        jLabel38.setBounds(20, 330, 60, 20);

        ADD7.setBackground(new java.awt.Color(224, 196, 160));
        ADD7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ADD7.setForeground(new java.awt.Color(255, 165, 31));
        ADD7.setText("Clear");
        ADD7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ADD7ActionPerformed(evt);
            }
        });
        jPanel18.add(ADD7);
        ADD7.setBounds(30, 540, 120, 20);

        category.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "appetizers", "salads", "soups", "main dishes", "desserts", "vegetarian", "seasonal" }));
        jPanel18.add(category);
        category.setBounds(100, 330, 180, 30);

        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Description:");
        jPanel18.add(jLabel14);
        jLabel14.setBounds(310, 20, 70, 20);

        jScrollPane1.setViewportView(Instruction);

        jPanel18.add(jScrollPane1);
        jScrollPane1.setBounds(400, 200, 190, 150);

        jScrollPane2.setViewportView(Description);

        jPanel18.add(jScrollPane2);
        jScrollPane2.setBounds(400, 20, 190, 150);

        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Image:");
        jPanel18.add(jLabel18);
        jLabel18.setBounds(10, 20, 70, 20);

        Title1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Title1ActionPerformed(evt);
            }
        });
        jPanel18.add(Title1);
        Title1.setBounds(100, 210, 180, 30);
        jPanel18.add(jDateChooser1);
        jDateChooser1.setBounds(100, 270, 180, 30);

        ADD8.setBackground(new java.awt.Color(255, 255, 255));
        ADD8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ADD8.setText("ADD");
        ADD8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ADD8ActionPerformed(evt);
            }
        });
        jPanel18.add(ADD8);
        ADD8.setBounds(400, 370, 190, 30);

        jPanel12.add(jPanel18);
        jPanel18.setBounds(20, 20, 670, 420);

        jPanel2.add(jPanel12);
        jPanel12.setBounds(30, 60, 710, 460);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0,80));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("ADD Recipe");
        jPanel1.add(jLabel9);

        jPanel2.add(jPanel1);
        jPanel1.setBounds(30, 10, 710, 40);

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/new back.png"))); // NOI18N
        jLabel12.setText("jLabel12");
        jPanel2.add(jLabel12);
        jLabel12.setBounds(0, 0, 770, 540);

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 770, 540));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField10ActionPerformed

    private void Title1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Title1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Title1ActionPerformed

    private void ADD8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ADD8ActionPerformed
        String title = Title1.getText().trim();
        String desc = Description.getText().trim();
        String instr = Instruction.getText().trim();
        String date = "";
        try {
            java.util.Date d = this.jDateChooser1.getDate();
            if (d != null) date = new SimpleDateFormat("yyyy-MM-dd").format(d);
        } catch (Exception ex) {
            date = "";
        }
        String cat = String.valueOf(category.getSelectedItem());
<<<<<<< HEAD
=======
        String ingName = jTextField5.getText().trim();
        String ingQty = jTextField7.getText().trim();
        String ingUnit = jTextField8.getText().trim();
        
        String ingredients = String.format("%s (%s %s)", ingName, ingQty, ingUnit);
>>>>>>> a8744219926975f3c37f4a6d807cbd64e7020fe1
        String author = config.Session.getInstance().getUsername() != null ? config.Session.getInstance().getUsername() : "Anonymous";

        if (title.isEmpty() || desc.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Title and Description are required");
            return;
        }

        con.ensureRecipesTable();
        
        try {
            if (recipeId == null) {
                // INSERT mode
                String sql = "INSERT INTO Recipes (r_title, r_description, r_author, r_category, r_date, r_instructions, r_ingredients) VALUES (?, ?, ?, ?, ?, ?, ?)";
                int newId = con.addRecordAndReturnId(sql, title, desc, author, cat, date, instr, "");
                JOptionPane.showMessageDialog(this, "Recipe added successfully!");
                // Ask whether to add ingredients
                int ask = JOptionPane.showConfirmDialog(this, "Do you want to add ingredients for this recipe now?", "Add Ingredients", JOptionPane.YES_NO_OPTION);
                if (ask == JOptionPane.YES_OPTION) {
                    new adding1(String.valueOf(newId), true).setVisible(true);
                    this.dispose();
                    return;
                }
            } else {
                // UPDATE mode
                String sql = "UPDATE Recipes SET r_title = ?, r_description = ?, r_category = ?, r_date = ?, r_instructions = ? WHERE r_id = ?";
                con.updateRecord(sql, title, desc, cat, date, instr, recipeId);
                JOptionPane.showMessageDialog(this, "Recipe updated successfully!");
            }
            
            // Navigate back to Manage
            Manage m = new Manage();
            m.setVisible(true);
            this.dispose();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error saving recipe: " + e.getMessage());
        }
    }//GEN-LAST:event_ADD8ActionPerformed

    private void ADD7ActionPerformed(java.awt.event.ActionEvent evt) {
        clearFields();
    }

    private void clearFields() {
        try { Title1.setText(""); } catch (Exception ignore) {}
        try { Description.setText(""); } catch (Exception ignore) {}
        try { Instruction.setText(""); } catch (Exception ignore) {}
        try { jDateChooser1.setDate(null); } catch (Exception ignore) {}
        try { if (category != null && category.getItemCount() > 0) { category.setSelectedIndex(0); } } catch (Exception ignore) {}
    }
    private void ADD3ActionPerformed(java.awt.event.ActionEvent evt) {
        Object[] options = {"Add Recipe", "Add Ingredients", "Cancel"};
        int choice = javax.swing.JOptionPane.showOptionDialog(this,
                "Choose action:",
                "Add",
                javax.swing.JOptionPane.DEFAULT_OPTION,
                javax.swing.JOptionPane.QUESTION_MESSAGE,
                null,
                options,
                options[0]);

        if (choice == 0) {
            // Trigger main ADD button to save recipe
            ADD8.doClick();
        } else if (choice == 1) {
            // Open Add Ingredients form (without a recipe yet)
            new adding1().setVisible(true);
            this.dispose();
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ADD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ADD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ADD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ADD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                if (config.Session.getInstance().isLoggedIn()) {
                    new ADD().setVisible(true);
                } else {
                    new landingPage1().setVisible(true);
                }
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ADD7;
    private javax.swing.JButton ADD8;
    private javax.swing.JTextField Description;
    private javax.swing.JTextField Instruction;
    private javax.swing.JTextField Title1;
    private java.awt.Canvas canvas1;
    private javax.swing.JComboBox<String> category;
    private java.awt.Choice choice1;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JDialog jDialog2;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JTextField jTextField10;
    // End of variables declaration//GEN-END:variables
}
