/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dishcovery;
import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public class ADD extends javax.swing.JFrame {
    private final config.config con = new config.config();
    private String recipeId = null;

    /**
     * Creates new form homePage2
     */
    public ADD() {
        config.Session.requireLogin(this);
        initComponents();
    }

    public ADD(String id) {
        config.Session.requireLogin(this);
        initComponents();
        this.recipeId = id;
        ADD8.setText("Update");
        jLabel9.setText("Update Recipe");
        populateFields(id);
    }

    private void populateFields(String id) {
        String sql = "SELECT * FROM Recipes WHERE r_id = ?";
        try (java.sql.Connection conn = con.connectDB();
             java.sql.PreparedStatement pstmt = conn.prepareStatement(sql)) {
            pstmt.setString(1, id);
            try (java.sql.ResultSet rs = pstmt.executeQuery()) {
                if (rs.next()) {
                    jTextField2.setText(rs.getString("r_title"));
                    jTextField11.setText(rs.getString("r_description"));
                    jTextField9.setText(rs.getString("r_instructions"));
                    jTextField6.setText(rs.getString("r_date"));
                    category.setSelectedItem(rs.getString("r_category"));
                    
                    String ingredients = rs.getString("r_ingredients");
                    if (ingredients != null && ingredients.contains("(")) {
                        try {
                            String name = ingredients.substring(0, ingredients.indexOf("(")).trim();
                            String rest = ingredients.substring(ingredients.indexOf("(") + 1, ingredients.indexOf(")"));
                            String[] parts = rest.split(" ");
                            if (parts.length >= 2) {
                                jTextField5.setText(name);
                                jTextField7.setText(parts[0]);
                                jTextField8.setText(parts[1]);
                            }
                        } catch (Exception e) {
                            jTextField5.setText(ingredients);
                        }
                    } else {
                        jTextField5.setText(ingredients);
                    }
                }
            }
        } catch (java.sql.SQLException e) {
            System.out.println("Error populating fields: " + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSpinner1 = new javax.swing.JSpinner();
        jPanel6 = new javax.swing.JPanel();
        jDialog1 = new javax.swing.JDialog();
        choice1 = new java.awt.Choice();
        canvas1 = new java.awt.Canvas();
        jDialog2 = new javax.swing.JDialog();
        jTextField10 = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jTextField6 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        ADD3 = new javax.swing.JButton();
        category = new javax.swing.JComboBox<>();
        ADD8 = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextField9 = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextField11 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        jPanel6.setBackground(new java.awt.Color(0, 0, 0,80));

        jTextField10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField10ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 390, -1, -1));

        jPanel2.setLayout(null);

        jPanel12.setBackground(new java.awt.Color(0, 0, 0,50));
        jPanel12.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel12.setLayout(null);

        jPanel3.setBackground(new java.awt.Color(0, 0, 0,80));
        jPanel3.setLayout(null);

        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Title:");
        jPanel3.add(jLabel11);
        jLabel11.setBounds(10, 30, 60, 20);

        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("SELECT");
        jPanel3.add(jLabel13);
        jLabel13.setBounds(650, 190, 70, 20);

        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Instruction:");
        jPanel3.add(jLabel15);
        jLabel15.setBounds(250, 210, 70, 20);

        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Date:");
        jPanel3.add(jLabel16);
        jLabel16.setBounds(10, 270, 60, 20);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.add(jPanel4);
        jPanel4.setBounds(590, 30, 170, 150);
        jPanel3.add(jTextField6);
        jTextField6.setBounds(70, 270, 160, 30);

        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Category:");
        jPanel3.add(jLabel17);
        jLabel17.setBounds(10, 330, 60, 20);

        ADD3.setBackground(new java.awt.Color(224, 196, 160));
        ADD3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ADD3.setForeground(new java.awt.Color(255, 165, 31));
        ADD3.setText("ADD");
        ADD3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ADD3ActionPerformed(evt);
            }
        });
        jPanel3.add(ADD3);
        ADD3.setBounds(30, 540, 120, 20);

        category.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "appetizers", "salads", "soups", "main dishes", "desserts", "vegetarian", "seasonal" }));
        category.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                categoryActionPerformed(evt);
            }
        });
        jPanel3.add(category);
        category.setBounds(70, 330, 160, 30);

        ADD8.setBackground(new java.awt.Color(255, 255, 255));
        ADD8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ADD8.setText("ADD");
        ADD8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ADD8ActionPerformed(evt);
            }
        });
        jPanel3.add(ADD8);
        ADD8.setBounds(590, 240, 170, 30);
        jPanel3.add(jTextField2);
        jTextField2.setBounds(70, 30, 160, 30);

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("name:");
        jPanel3.add(jLabel19);
        jLabel19.setBounds(10, 90, 70, 20);
        jPanel3.add(jTextField5);
        jTextField5.setBounds(70, 90, 160, 30);

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Quantity:");
        jPanel3.add(jLabel20);
        jLabel20.setBounds(10, 150, 60, 20);
        jPanel3.add(jTextField7);
        jTextField7.setBounds(70, 150, 160, 30);

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Unit:");
        jPanel3.add(jLabel21);
        jLabel21.setBounds(10, 210, 60, 20);
        jPanel3.add(jTextField8);
        jTextField8.setBounds(70, 210, 160, 30);

        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Description:");
        jPanel3.add(jLabel14);
        jLabel14.setBounds(250, 30, 70, 20);

        jTextField9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField9ActionPerformed(evt);
            }
        });
        jScrollPane1.setViewportView(jTextField9);

        jPanel3.add(jScrollPane1);
        jScrollPane1.setBounds(320, 210, 190, 150);

        jTextField11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField11ActionPerformed(evt);
            }
        });
        jScrollPane2.setViewportView(jTextField11);

        jPanel3.add(jScrollPane2);
        jScrollPane2.setBounds(320, 30, 190, 150);

        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Image:");
        jPanel3.add(jLabel18);
        jLabel18.setBounds(540, 30, 70, 20);

        jPanel12.add(jPanel3);
        jPanel3.setBounds(30, 30, 790, 400);

        jPanel2.add(jPanel12);
        jPanel12.setBounds(20, 70, 840, 460);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0,80));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("ADD Recipe");
        jPanel1.add(jLabel9);

        jPanel2.add(jPanel1);
        jPanel1.setBounds(20, 20, 840, 40);

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/new back.png"))); // NOI18N
        jLabel12.setText("jLabel12");
        jPanel2.add(jLabel12);
        jLabel12.setBounds(0, -10, 880, 560);

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 880, 550));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void categoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_categoryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_categoryActionPerformed

    private void ADD8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ADD8ActionPerformed
        String title = jTextField2.getText().trim();
        String desc = jTextField11.getText().trim();
        String instr = jTextField9.getText().trim();
        String date = jTextField6.getText().trim();
        String cat = String.valueOf(category.getSelectedItem());
        String ingName = jTextField5.getText().trim();
        String ingQty = jTextField7.getText().trim();
        String ingUnit = jTextField8.getText().trim();
        
        String ingredients = String.format("%s (%s %s)", ingName, ingQty, ingUnit);
        String author = config.Session.getInstance().getUsername() != null ? config.Session.getInstance().getUsername() : "Anonymous";

        if (title.isEmpty() || desc.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Title and Description are required");
            return;
        }

        con.ensureRecipesTable();
        
        try {
            if (recipeId == null) {
                // INSERT mode
                String sql = "INSERT INTO Recipes (r_title, r_description, r_author, r_category, r_date, r_instructions, r_ingredients) VALUES (?, ?, ?, ?, ?, ?, ?)";
                con.addRecord(sql, title, desc, author, cat, date, instr, ingredients);
                JOptionPane.showMessageDialog(this, "Recipe added successfully!");
            } else {
                // UPDATE mode
                String sql = "UPDATE Recipes SET r_title = ?, r_description = ?, r_category = ?, r_date = ?, r_instructions = ?, r_ingredients = ? WHERE r_id = ?";
                con.updateRecord(sql, title, desc, cat, date, instr, ingredients, recipeId);
                JOptionPane.showMessageDialog(this, "Recipe updated successfully!");
            }
            
            // Clear fields and navigate back
            jTextField2.setText("");
            jTextField11.setText("");
            jTextField9.setText("");
            jTextField6.setText("");
            jTextField5.setText("");
            jTextField7.setText("");
            jTextField8.setText("");
            
            // Navigate back to Manage
            Manage m = new Manage();
            m.setVisible(true);
            this.dispose();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error saving recipe: " + e.getMessage());
        }
    }//GEN-LAST:event_ADD8ActionPerformed

    private void jTextField9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField9ActionPerformed

    private void jTextField10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField10ActionPerformed

    private void jTextField11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField11ActionPerformed
    private void ADD3ActionPerformed(java.awt.event.ActionEvent evt) { ADD8ActionPerformed(evt); }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ADD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ADD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ADD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ADD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ADD().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ADD3;
    private javax.swing.JButton ADD8;
    private java.awt.Canvas canvas1;
    private javax.swing.JComboBox<String> category;
    private java.awt.Choice choice1;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JDialog jDialog2;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
