/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dishcovery;
import java.awt.Insets;
import java.text.SimpleDateFormat;
import javax.swing.JScrollPane;
import javax.swing.JTabbedPane;
import javax.swing.JPanel;
import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public class adding extends javax.swing.JFrame {
    private final config.config con = new config.config();
    private String recipeId = null;

    /**
     * Creates new form homePage2
     */
    public adding() {
        config.Session.requireLogin(this);
        initComponents();
    }

    public adding(String id) {
        config.Session.requireLogin(this);
        initComponents();
        this.recipeId = id;
        DONE.setText("Update");
        jLabel9.setText("Update Recipe");
        populateFields(id);
    }

    

    private void populateFields(String id) {
        String sql = "SELECT * FROM Recipes WHERE r_id = ?";
        try (java.sql.Connection conn = con.connectDB();
             java.sql.PreparedStatement pstmt = conn.prepareStatement(sql)) {
            pstmt.setString(1, id);
            try (java.sql.ResultSet rs = pstmt.executeQuery()) {
                if (rs.next()) {
                    Unit.setText(rs.getString("r_title"));
                    jTextField11.setText(rs.getString("r_description"));
                    jTextField9.setText(rs.getString("r_instructions"));
                    String dateStr = rs.getString("r_date");
                    if (dateStr != null && !dateStr.isEmpty()) {
                        // parsed date available but no date chooser UI in this variant
                        try {
                            java.util.Date parsed = new SimpleDateFormat("yyyy-MM-dd").parse(dateStr);
                            // parsed can be used if needed; currently not applied to a UI component
                        } catch (Exception ex) {
                        }
                    }
                    category.setSelectedItem(rs.getString("r_category"));
                    
                    String ingredients = rs.getString("r_ingredients");
                    if (ingredients != null && ingredients.contains("(")) {
                        try {
                            String name = ingredients.substring(0, ingredients.indexOf("(")).trim();
                            String rest = ingredients.substring(ingredients.indexOf("(") + 1, ingredients.indexOf(")"));
                            String[] parts = rest.split(" ");
                            if (parts.length >= 2) {
                                jTextField5.setText(name);
                                jTextField7.setText(parts[0]);
                                jTextField8.setText(parts[1]);
                            }
                        } catch (Exception e) {
                            jTextField5.setText(ingredients);
                        }
                    } else {
                        jTextField5.setText(ingredients);
                    }
                }
            }
        } catch (java.sql.SQLException e) {
            System.out.println("Error populating fields: " + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSpinner1 = new javax.swing.JSpinner();
        jPanel6 = new javax.swing.JPanel();
        jDialog1 = new javax.swing.JDialog();
        choice1 = new java.awt.Choice();
        canvas1 = new java.awt.Canvas();
        jDialog2 = new javax.swing.JDialog();
        jTextField10 = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jPanel18 = new javax.swing.JPanel();
        jLabel34 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        ADD7 = new javax.swing.JButton();
        DONE = new javax.swing.JButton();
        Unit = new javax.swing.JTextField();
        name = new javax.swing.JTextField();
        Quantity = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        ingredientsTable = new javax.swing.JTable();
        Name = new javax.swing.JLabel();
        ADD9 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        jPanel6.setBackground(new java.awt.Color(0, 0, 0,80));

        jTextField10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField10ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 390, -1, -1));

        jPanel2.setLayout(null);

        jPanel12.setBackground(new java.awt.Color(0, 0, 0,50));
        jPanel12.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel12.setLayout(null);

        jPanel18.setBackground(new java.awt.Color(0, 0, 0,80));
        jPanel18.setLayout(null);

        jLabel34.setForeground(new java.awt.Color(255, 255, 255));
        jLabel34.setText("name:");
        jPanel18.add(jLabel34);
        jLabel34.setBounds(20, 70, 60, 20);

        jLabel37.setForeground(new java.awt.Color(255, 255, 255));
        jLabel37.setText("Quantity:");
        jPanel18.add(jLabel37);
        jLabel37.setBounds(20, 130, 60, 20);

        jLabel38.setForeground(new java.awt.Color(255, 255, 255));
        jLabel38.setText("Unit:");
        jPanel18.add(jLabel38);
        jLabel38.setBounds(20, 190, 60, 20);

        ADD7.setBackground(new java.awt.Color(224, 196, 160));
        ADD7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ADD7.setForeground(new java.awt.Color(255, 165, 31));
        ADD7.setText("ADD");
        jPanel18.add(ADD7);
        ADD7.setBounds(30, 540, 120, 20);

        DONE.setBackground(new java.awt.Color(255, 255, 255));
        DONE.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        DONE.setText("DONE");
        DONE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DONEActionPerformed(evt);
            }
        });
        jPanel18.add(DONE);
        DONE.setBounds(90, 240, 90, 30);

        Unit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UnitActionPerformed(evt);
            }
        });
        jPanel18.add(Unit);
        Unit.setBounds(90, 190, 190, 30);

        name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameActionPerformed(evt);
            }
        });
        jPanel18.add(name);
        name.setBounds(90, 70, 190, 30);

        Quantity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QuantityActionPerformed(evt);
            }
        });
        jPanel18.add(Quantity);
        Quantity.setBounds(90, 130, 190, 30);

        ingredientsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        ingredientsTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ingredientsTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(ingredientsTable);

        jPanel18.add(jScrollPane1);
        jScrollPane1.setBounds(300, 70, 360, 200);

        Name.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Name.setForeground(new java.awt.Color(255, 255, 255));
        Name.setText("Name");
        jPanel18.add(Name);
        Name.setBounds(260, 10, 240, 32);

        ADD9.setBackground(new java.awt.Color(255, 255, 255));
        ADD9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ADD9.setText("ADD");
        ADD9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ADD9ActionPerformed(evt);
            }
        });
        jPanel18.add(ADD9);
        ADD9.setBounds(190, 240, 90, 30);

        jPanel12.add(jPanel18);
        jPanel18.setBounds(20, 20, 670, 300);

        jPanel2.add(jPanel12);
        jPanel12.setBounds(30, 60, 710, 340);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0,80));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("ADD INGREDIENTS");
        jPanel1.add(jLabel9);

        jPanel2.add(jPanel1);
        jPanel1.setBounds(30, 10, 710, 40);

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/new back.png"))); // NOI18N
        jLabel12.setText("jLabel12");
        jPanel2.add(jLabel12);
        jLabel12.setBounds(0, 0, 770, 420);

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 770, 420));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField10ActionPerformed

    private void ADD9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ADD9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ADD9ActionPerformed

    private void ingredientsTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ingredientsTableMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_ingredientsTableMouseClicked

    private void QuantityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QuantityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_QuantityActionPerformed

    private void nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameActionPerformed

    private void UnitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UnitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UnitActionPerformed

    private void DONEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DONEActionPerformed
        String title = Unit.getText().trim();
        String desc = jTextField11.getText().trim();
        String instr = jTextField9.getText().trim();
        String date = "";
        // No date chooser in this form; leave date empty unless set elsewhere
        String cat = String.valueOf(category.getSelectedItem());
        String author = config.Session.getInstance().getUsername() != null ? config.Session.getInstance().getUsername() : "Anonymous";

        if (title.isEmpty() || desc.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Title and Description are required");
            return;
        }

        con.ensureRecipesTable();

        try {
            if (recipeId == null) {
                // INSERT mode
                String sql = "INSERT INTO Recipes (r_title, r_description, r_author, r_category, r_date, r_instructions, r_ingredients) VALUES (?, ?, ?, ?, ?, ?, ?)";
                int newId = con.addRecordAndReturnId(sql, title, desc, author, cat, date, instr, "");
                JOptionPane.showMessageDialog(this, "Recipe added successfully!");
                // Ask whether to add ingredients
                int ask = JOptionPane.showConfirmDialog(this, "Do you want to add ingredients for this recipe now?", "Add Ingredients", JOptionPane.YES_NO_OPTION);
                if (ask == JOptionPane.YES_OPTION) {
                    new ADDingredients(newId).setVisible(true);
                    this.dispose();
                    return;
                }
            } else {
                // UPDATE mode
                String sql = "UPDATE Recipes SET r_title = ?, r_description = ?, r_category = ?, r_date = ?, r_instructions = ? WHERE r_id = ?";
                con.updateRecord(sql, title, desc, cat, date, instr, recipeId);
                JOptionPane.showMessageDialog(this, "Recipe updated successfully!");
            }

            // Navigate back to Manage
            Manage m = new Manage();
            m.setVisible(true);
            this.dispose();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error saving recipe: " + e.getMessage());
        }
    }//GEN-LAST:event_DONEActionPerformed
    private void ADD3ActionPerformed(java.awt.event.ActionEvent evt) {
        Object[] options = {"Add Recipe", "Add Ingredients", "Cancel"};
        int choice = javax.swing.JOptionPane.showOptionDialog(this,
                "Choose action:",
                "Add",
                javax.swing.JOptionPane.DEFAULT_OPTION,
                javax.swing.JOptionPane.QUESTION_MESSAGE,
                null,
                options,
                options[0]);

        if (choice == 0) {
            // Trigger main ADD button to save recipe
            DONE.doClick();
        } else if (choice == 1) {
            // Open Add Ingredients form (without a recipe yet)
            new ADDingredients().setVisible(true);
            this.dispose();
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(adding.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(adding.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(adding.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(adding.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new adding().setVisible(true);
            }
        });
    }

    // Allow other forms to pre-fill ingredient fields when returning from a helper form
    public void setIngredientFields(String name, String qty, String unit) {
        if (name == null) name = "";
        if (qty == null) qty = "";
        if (unit == null) unit = "";
        jTextField5.setText(name);
        jTextField7.setText(qty);
        jTextField8.setText(unit);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ADD7;
    private javax.swing.JButton ADD9;
    private javax.swing.JButton DONE;
    private javax.swing.JLabel Name;
    private javax.swing.JTextField Quantity;
    private javax.swing.JTextField Unit;
    private java.awt.Canvas canvas1;
    private java.awt.Choice choice1;
    private javax.swing.JTable ingredientsTable;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JDialog jDialog2;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField name;
    // End of variables declaration//GEN-END:variables
}
