/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dishcovery;
import config.config;
import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public class Delete extends javax.swing.JFrame {
    private final config con = new config();

    /**
     * Creates new form homePage2
     */
    public Delete() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSpinner1 = new javax.swing.JSpinner();
        jPanel6 = new javax.swing.JPanel();
        jDialog1 = new javax.swing.JDialog();
        choice1 = new java.awt.Choice();
        canvas1 = new java.awt.Canvas();
        jDialog2 = new javax.swing.JDialog();
        jScrollPane3 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        ADD3 = new javax.swing.JButton();
        ADD8 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        ADD9 = new javax.swing.JButton();
        jLabel27 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        ADD13 = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        ADD7 = new javax.swing.JButton();
        ADD11 = new javax.swing.JButton();
        ADD12 = new javax.swing.JButton();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jPanel16 = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        ADD30 = new javax.swing.JButton();
        ADD31 = new javax.swing.JButton();
        ADD32 = new javax.swing.JButton();
        ADD33 = new javax.swing.JButton();
        ADD34 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();

        jPanel6.setBackground(new java.awt.Color(0, 0, 0,80));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 390, -1, -1));

        jPanel2.setLayout(null);

        jPanel12.setBackground(new java.awt.Color(0, 0, 0,50));
        jPanel12.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel12.setLayout(null);

        jTabbedPane1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(null);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 165, 31));
        jLabel9.setText("Delete Recipe");
        jPanel3.add(jLabel9);
        jLabel9.setBounds(30, 10, 120, 20);
        jPanel3.add(jTextField1);
        jTextField1.setBounds(10, 70, 160, 20);

        jLabel11.setForeground(new java.awt.Color(255, 165, 31));
        jLabel11.setText("Recipe ID");
        jPanel3.add(jLabel11);
        jLabel11.setBounds(10, 50, 60, 20);

        ADD3.setBackground(new java.awt.Color(224, 196, 160));
        ADD3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ADD3.setForeground(new java.awt.Color(255, 165, 31));
        ADD3.setText("ADD");
        ADD3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ADD3ActionPerformed(evt);
            }
        });
        jPanel3.add(ADD3);
        ADD3.setBounds(30, 540, 120, 20);

        ADD8.setBackground(new java.awt.Color(224, 196, 160));
        ADD8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ADD8.setForeground(new java.awt.Color(255, 165, 31));
        ADD8.setText("Delete");
        ADD8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ADD8ActionPerformed(evt);
            }
        });
        jPanel3.add(ADD8);
        ADD8.setBounds(40, 100, 100, 30);

        jTabbedPane1.addTab("Recipe", jPanel3);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(null);

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 165, 31));
        jLabel14.setText("ADD Ingredients");
        jPanel4.add(jLabel14);
        jLabel14.setBounds(20, 10, 150, 30);

        ADD9.setBackground(new java.awt.Color(224, 196, 160));
        ADD9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ADD9.setForeground(new java.awt.Color(255, 165, 31));
        ADD9.setText("ADD");
        ADD9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ADD9ActionPerformed(evt);
            }
        });
        jPanel4.add(ADD9);
        ADD9.setBounds(30, 540, 120, 20);

        jLabel27.setForeground(new java.awt.Color(255, 165, 31));
        jLabel27.setText("Recipe ID");
        jPanel4.add(jLabel27);
        jLabel27.setBounds(10, 50, 60, 20);
        jPanel4.add(jTextField9);
        jTextField9.setBounds(10, 70, 160, 20);

        ADD13.setBackground(new java.awt.Color(224, 196, 160));
        ADD13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ADD13.setForeground(new java.awt.Color(255, 165, 31));
        ADD13.setText("Delete");
        ADD13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ADD13ActionPerformed(evt);
            }
        });
        jPanel4.add(ADD13);
        ADD13.setBounds(40, 100, 100, 30);

        jTabbedPane1.addTab("Ingredients", jPanel4);

        jPanel12.add(jTabbedPane1);
        jTabbedPane1.setBounds(220, 20, 190, 180);

        jPanel8.setBackground(new java.awt.Color(0, 0, 0,80));
        jPanel8.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel8.setLayout(null);

        jLabel22.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 165, 31));
        jLabel22.setText("Manage");
        jLabel22.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel22MouseClicked(evt);
            }
        });
        jPanel8.add(jLabel22);
        jLabel22.setBounds(580, 0, 60, 30);

        ADD7.setBackground(new java.awt.Color(224, 196, 160));
        ADD7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ADD7.setForeground(new java.awt.Color(255, 165, 31));
        ADD7.setText("Delete");
        ADD7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ADD7MouseClicked(evt);
            }
        });
        ADD7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ADD7ActionPerformed(evt);
            }
        });
        jPanel8.add(ADD7);
        ADD7.setBounds(270, 10, 80, 30);

        ADD11.setBackground(new java.awt.Color(224, 196, 160));
        ADD11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ADD11.setForeground(new java.awt.Color(255, 165, 31));
        ADD11.setText("ADD");
        ADD11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ADD11MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ADD11MouseEntered(evt);
            }
        });
        ADD11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ADD11ActionPerformed(evt);
            }
        });
        jPanel8.add(ADD11);
        ADD11.setBounds(30, 10, 80, 30);

        ADD12.setBackground(new java.awt.Color(224, 196, 160));
        ADD12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ADD12.setForeground(new java.awt.Color(255, 165, 31));
        ADD12.setText("Update");
        ADD12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ADD12MouseClicked(evt);
            }
        });
        ADD12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ADD12ActionPerformed(evt);
            }
        });
        jPanel8.add(ADD12);
        ADD12.setBounds(150, 10, 90, 30);

        jPanel12.add(jPanel8);
        jPanel8.setBounds(430, 20, 370, 50);

        jTabbedPane2.setBackground(new java.awt.Color(255, 255, 255));
        jTabbedPane2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jPanel5.setBackground(new java.awt.Color(0, 0, 0,80));
        jPanel5.setLayout(null);

        jTable1.setBackground(new java.awt.Color(0, 0, 0,80));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Recipe ID", "Tittle", "Descrition", "date", "status", "Category"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel5.add(jScrollPane1);
        jScrollPane1.setBounds(0, 0, 390, 350);

        jTabbedPane2.addTab("recipe", jPanel5);

        jTable3.setBackground(new java.awt.Color(0, 0, 0,80));
        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Recipe ID", "Tittle", "Descrition", "date", "status", "Category"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(jTable3);

        jTabbedPane2.addTab("Ingredients", jScrollPane4);

        jPanel12.add(jTabbedPane2);
        jTabbedPane2.setBounds(430, 90, 370, 370);

        jPanel16.setBackground(new java.awt.Color(0, 0, 0,60));
        jPanel16.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel16.setLayout(null);

        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/small logo.png"))); // NOI18N
        jLabel28.setText("jLabel9");
        jPanel16.add(jLabel28);
        jLabel28.setBounds(10, 10, 140, 120);

        ADD30.setBackground(new java.awt.Color(255, 255, 255));
        ADD30.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ADD30.setText("View");
        ADD30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ADD30ActionPerformed(evt);
            }
        });
        jPanel16.add(ADD30);
        ADD30.setBounds(40, 270, 90, 30);

        ADD31.setBackground(new java.awt.Color(255, 255, 255));
        ADD31.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ADD31.setText("Share");
        ADD31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ADD31ActionPerformed(evt);
            }
        });
        jPanel16.add(ADD31);
        ADD31.setBounds(40, 320, 90, 30);

        ADD32.setBackground(new java.awt.Color(255, 255, 255));
        ADD32.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ADD32.setText("Profile");
        ADD32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ADD32ActionPerformed(evt);
            }
        });
        jPanel16.add(ADD32);
        ADD32.setBounds(40, 370, 90, 30);

        ADD33.setBackground(new java.awt.Color(255, 255, 255));
        ADD33.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ADD33.setText("Manage");
        ADD33.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ADD33MouseClicked(evt);
            }
        });
        ADD33.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ADD33ActionPerformed(evt);
            }
        });
        jPanel16.add(ADD33);
        ADD33.setBounds(40, 220, 90, 30);

        ADD34.setBackground(new java.awt.Color(255, 255, 255));
        ADD34.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ADD34.setText("Home");
        ADD34.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ADD34MouseClicked(evt);
            }
        });
        ADD34.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ADD34ActionPerformed(evt);
            }
        });
        jPanel16.add(ADD34);
        ADD34.setBounds(40, 170, 90, 30);

        jPanel12.add(jPanel16);
        jPanel16.setBounds(20, 20, 180, 470);

        jPanel2.add(jPanel12);
        jPanel12.setBounds(20, 30, 840, 510);

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/new back.png"))); // NOI18N
        jLabel12.setText("jLabel12");
        jPanel2.add(jLabel12);
        jLabel12.setBounds(0, -10, 880, 590);

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 930, 570));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel22MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel22MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel22MouseClicked

    private void ADD7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ADD7MouseClicked
        Delete l = new Delete();
        l.setVisible(true);
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_ADD7MouseClicked

    private void ADD7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ADD7ActionPerformed
        Delete l = new Delete();
        l.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ADD7ActionPerformed

    private void ADD11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ADD11MouseClicked
        Manage l = new Manage();
        l.setVisible(true);
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_ADD11MouseClicked

    private void ADD11MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ADD11MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_ADD11MouseEntered

    private void ADD11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ADD11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ADD11ActionPerformed

    private void ADD12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ADD12MouseClicked
        Update l = new Update();
        l.setVisible(true);
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_ADD12MouseClicked

    private void ADD12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ADD12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ADD12ActionPerformed

    private void ADD9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ADD9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ADD9ActionPerformed

    private void ADD8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ADD8ActionPerformed
        String idText = jTextField1.getText().trim();
        if (idText.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter a Recipe ID");
            return;
        }
        int id = -1;
        try { id = Integer.parseInt(idText); } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Recipe ID must be a number");
            return;
        }
        con.ensureRecipesTable();
        boolean exists = con.existsRecord("SELECT 1 FROM Recipes WHERE r_id = ?", id);
        if (!exists) {
            JOptionPane.showMessageDialog(this, "Recipe not found");
            return;
        }
        con.deleteRecord("DELETE FROM Recipes WHERE r_id = ?", id);
        JOptionPane.showMessageDialog(this, "Recipe deleted");
    }//GEN-LAST:event_ADD8ActionPerformed

    private void ADD3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ADD3ActionPerformed
        JOptionPane.showMessageDialog(this, "Action not implemented");
    }//GEN-LAST:event_ADD3ActionPerformed

    private void ADD13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ADD13ActionPerformed
        String idText = jTextField9.getText().trim();
        if (idText.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter a Recipe ID");
            return;
        }
        int id = -1;
        try { id = Integer.parseInt(idText); } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Recipe ID must be a number");
            return;
        }
        boolean ingredientsTable = con.existsRecord("SELECT 1 FROM sqlite_master WHERE type='table' AND name='Ingredients'");
        if (!ingredientsTable) {
            JOptionPane.showMessageDialog(this, "Ingredients table not found");
            return;
        }
        con.deleteRecord("DELETE FROM Ingredients WHERE r_id = ?", id);
        JOptionPane.showMessageDialog(this, "Ingredients deleted for Recipe ID " + id);
    }//GEN-LAST:event_ADD13ActionPerformed

    private void ADD30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ADD30ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ADD30ActionPerformed

    private void ADD31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ADD31ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ADD31ActionPerformed

    private void ADD32ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ADD32ActionPerformed
        profile l = new profile();
        l.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ADD32ActionPerformed

    private void ADD33MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ADD33MouseClicked
        Manage l = new Manage();
        l.setVisible(true);
        this.dispose();         // TODO add your handling code here:
    }//GEN-LAST:event_ADD33MouseClicked

    private void ADD33ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ADD33ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ADD33ActionPerformed

    private void ADD34MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ADD34MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_ADD34MouseClicked

    private void ADD34ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ADD34ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ADD34ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Delete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Delete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Delete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Delete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Delete().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ADD11;
    private javax.swing.JButton ADD12;
    private javax.swing.JButton ADD13;
    private javax.swing.JButton ADD3;
    private javax.swing.JButton ADD30;
    private javax.swing.JButton ADD31;
    private javax.swing.JButton ADD32;
    private javax.swing.JButton ADD33;
    private javax.swing.JButton ADD34;
    private javax.swing.JButton ADD7;
    private javax.swing.JButton ADD8;
    private javax.swing.JButton ADD9;
    private java.awt.Canvas canvas1;
    private java.awt.Choice choice1;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JDialog jDialog2;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
