/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dishcovery;

import config.config;
import javax.swing.JScrollPane;
import javax.swing.JTable;

/**
 *
 * @author user
 */
public class homePage2 extends javax.swing.JFrame {
    private final config con = new config();

    /**
     * Creates new form homePage2
     */
    public homePage2() {
        initComponents();
        displayRecipes();
    }

    private void displayRecipes() {
        String sql = "SELECT r_id AS ID, r_title AS Title, r_author AS Author, r_category AS Category, r_date AS Date FROM Recipes";
        con.displayData(sql, table_recipe);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSpinner1 = new javax.swing.JSpinner();
        jPanel6 = new javax.swing.JPanel();
        jDialog1 = new javax.swing.JDialog();
        choice1 = new java.awt.Choice();
        canvas1 = new java.awt.Canvas();
        jDialog2 = new javax.swing.JDialog();
        jScrollPane3 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel16 = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        ADD30 = new javax.swing.JButton();
        ADD31 = new javax.swing.JButton();
        ADD32 = new javax.swing.JButton();
        ADD33 = new javax.swing.JButton();
        ADD34 = new javax.swing.JButton();
        jPanel13 = new javax.swing.JPanel();
        Search1 = new javax.swing.JTextField();
        view = new javax.swing.JButton();
        category = new javax.swing.JComboBox<>();
        search = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();

        jPanel6.setBackground(new java.awt.Color(0, 0, 0,80));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 390, -1, -1));

        jPanel2.setLayout(null);

        jPanel8.setBackground(new java.awt.Color(0, 0, 0,50));
        jPanel8.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel8.setLayout(null);

        jPanel5.setBackground(new java.awt.Color(0, 0, 0,60));
        jPanel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel5.setLayout(null);
        jPanel8.add(jPanel5);
        jPanel5.setBounds(230, 70, 590, 420);

        jScrollPane1 = new JScrollPane();
        table_recipe = new JTable();
        table_recipe.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(table_recipe);
        jPanel5.add(jScrollPane1);
        jScrollPane1.setBounds(0, 0, 590, 420);

        jPanel16.setBackground(new java.awt.Color(0, 0, 0,60));
        jPanel16.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel16.setLayout(null);

        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/small logo.png"))); // NOI18N
        jLabel27.setText("jLabel9");
        jPanel16.add(jLabel27);
        jLabel27.setBounds(10, 10, 140, 120);

        ADD30.setBackground(new java.awt.Color(255, 255, 255));
        ADD30.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ADD30.setText("View");
        ADD30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ADD30ActionPerformed(evt);
            }
        });
        jPanel16.add(ADD30);
        ADD30.setBounds(40, 270, 90, 30);

        ADD31.setBackground(new java.awt.Color(255, 255, 255));
        ADD31.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ADD31.setText("Share");
        ADD31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ADD31ActionPerformed(evt);
            }
        });
        jPanel16.add(ADD31);
        ADD31.setBounds(40, 320, 90, 30);

        ADD32.setBackground(new java.awt.Color(255, 255, 255));
        ADD32.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ADD32.setText("Profile");
        ADD32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ADD32ActionPerformed(evt);
            }
        });
        jPanel16.add(ADD32);
        ADD32.setBounds(40, 370, 90, 30);

        ADD33.setBackground(new java.awt.Color(255, 255, 255));
        ADD33.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ADD33.setText("Manage");
        ADD33.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ADD33MouseClicked(evt);
            }
        });
        ADD33.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ADD33ActionPerformed(evt);
            }
        });
        jPanel16.add(ADD33);
        ADD33.setBounds(40, 220, 90, 30);

        ADD34.setBackground(new java.awt.Color(255, 255, 255));
        ADD34.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ADD34.setText("Home");
        ADD34.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ADD34MouseClicked(evt);
            }
        });
        ADD34.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ADD34ActionPerformed(evt);
            }
        });
        jPanel16.add(ADD34);
        ADD34.setBounds(40, 170, 90, 30);

        jPanel8.add(jPanel16);
        jPanel16.setBounds(20, 20, 180, 470);

        jPanel13.setBackground(new java.awt.Color(0, 0, 0,60));
        jPanel13.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel13.setLayout(null);

        Search1.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        Search1.setText("Search recipes by name or ID");
        Search1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Search1ActionPerformed(evt);
            }
        });
        Search1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                Search1KeyReleased(evt);
            }
        });
        Search1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                Search1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                Search1FocusLost(evt);
            }
        });
        jPanel13.add(Search1);
        Search1.setBounds(10, 10, 270, 30);

        view.setBackground(new java.awt.Color(255, 255, 255));
        view.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        view.setText("View");
        view.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewActionPerformed(evt);
            }
        });
        jPanel13.add(view);
        view.setBounds(390, 10, 83, 30);

        category.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "appetizers", "salads", "soups", "main dishes", "desserts", "vegetarian", "seasonal" }));
        category.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                categoryActionPerformed(evt);
            }
        });
        jPanel13.add(category);
        category.setBounds(490, 10, 90, 30);

        search.setBackground(new java.awt.Color(255, 255, 255));
        search.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        search.setText("Search");
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });
        jPanel13.add(search);
        search.setBounds(290, 10, 80, 30);

        jPanel8.add(jPanel13);
        jPanel13.setBounds(230, 20, 590, 50);

        jPanel2.add(jPanel8);
        jPanel8.setBounds(20, 30, 840, 510);

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/new back.png"))); // NOI18N
        jLabel12.setText("jLabel12");
        jPanel2.add(jLabel12);
        jLabel12.setBounds(0, -10, 880, 590);

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 880, 570));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ADD30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ADD30ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ADD30ActionPerformed

    private void ADD31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ADD31ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ADD31ActionPerformed

    private void ADD32ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ADD32ActionPerformed
        profileadmin l = new profileadmin();
        l.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_ADD32ActionPerformed

    private void ADD33MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ADD33MouseClicked
        Manage l = new Manage();
        l.setVisible(true);
        this.dispose();         // TODO add your handling code here:
    }//GEN-LAST:event_ADD33MouseClicked

    private void ADD33ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ADD33ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ADD33ActionPerformed

    private void ADD34MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ADD34MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_ADD34MouseClicked

    private void ADD34ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ADD34ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ADD34ActionPerformed

    private void Search1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Search1ActionPerformed
        performSearch();
    }//GEN-LAST:event_Search1ActionPerformed

    private void viewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewActionPerformed
        Search1.setText("");
        if (category.getItemCount() > 0) {
            category.setSelectedIndex(0);
        }
        displayRecipes();
    }//GEN-LAST:event_viewActionPerformed

    private void categoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_categoryActionPerformed
        performSearch();
    }//GEN-LAST:event_categoryActionPerformed

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        performSearch();
    }//GEN-LAST:event_searchActionPerformed

    private void Search1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Search1KeyReleased
        performSearch();
    }//GEN-LAST:event_Search1KeyReleased

    private void Search1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Search1FocusGained
        if ("Search recipes by name or ID".equals(Search1.getText())) {
            Search1.setText("");
        }
    }//GEN-LAST:event_Search1FocusGained

    private void Search1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Search1FocusLost
        if (Search1.getText().trim().isEmpty()) {
            Search1.setText("Search recipes by name or ID");
        }
    }//GEN-LAST:event_Search1FocusLost

    private void performSearch() {
        String txt = Search1.getText() != null ? Search1.getText().trim() : "";
        if ("Search recipes by name or ID".equals(txt)) txt = "";
        String cat = category.getSelectedItem() != null ? category.getSelectedItem().toString() : "";
        StringBuilder sql = new StringBuilder("SELECT r_id AS ID, r_title AS Title, r_author AS Author, r_category AS Category, r_date AS Date FROM Recipes WHERE 1=1");
        java.util.List<Object> params = new java.util.ArrayList<>();
        if (!txt.isEmpty()) {
            sql.append(" AND (r_title LIKE ? OR CAST(r_id AS TEXT) LIKE ? OR r_author LIKE ?)");
            params.add("%" + txt + "%");
            params.add("%" + txt + "%");
            params.add("%" + txt + "%");
        }
        if (!cat.isEmpty()) {
            sql.append(" AND r_category = ?");
            params.add(cat);
        }
        con.displayData(sql.toString(), table_recipe, params.toArray());
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(homePage2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(homePage2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(homePage2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(homePage2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new homePage2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ADD30;
    private javax.swing.JButton ADD31;
    private javax.swing.JButton ADD32;
    private javax.swing.JButton ADD33;
    private javax.swing.JButton ADD34;
    private javax.swing.JTextField Search1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table_recipe;
    private java.awt.Canvas canvas1;
    private javax.swing.JComboBox<String> category;
    private java.awt.Choice choice1;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JDialog jDialog2;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JButton search;
    private javax.swing.JButton view;
    // End of variables declaration//GEN-END:variables
}
