/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dishcovery;

/**
 *
 * @author user
 */
public class homePage2 extends javax.swing.JFrame {

    /**
     * Creates new form homePage2
     */
    public homePage2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSpinner1 = new javax.swing.JSpinner();
        jPanel6 = new javax.swing.JPanel();
        jDialog1 = new javax.swing.JDialog();
        choice1 = new java.awt.Choice();
        canvas1 = new java.awt.Canvas();
        jDialog2 = new javax.swing.JDialog();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        Search = new javax.swing.JTextField();
        ADD7 = new javax.swing.JButton();
        category = new javax.swing.JComboBox<>();
        ADD10 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jPanel15 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        ADD22 = new javax.swing.JButton();
        ADD23 = new javax.swing.JButton();
        ADD24 = new javax.swing.JButton();
        ADD25 = new javax.swing.JButton();
        ADD26 = new javax.swing.JButton();
        ADD27 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();

        jPanel6.setBackground(new java.awt.Color(0, 0, 0,80));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0,80));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 165, 31));
        jLabel1.setText("X");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel1);
        jLabel1.setBounds(840, 0, 20, 30);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 165, 31));
        jLabel4.setText("Dishcovery");
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel4);
        jLabel4.setBounds(20, 0, 100, 30);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 880, 30));
        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 390, -1, -1));

        jPanel2.setLayout(null);

        jPanel8.setBackground(new java.awt.Color(0, 0, 0,50));
        jPanel8.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel8.setLayout(null);

        jPanel7.setBackground(new java.awt.Color(0, 0, 0,60));
        jPanel7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel7.setLayout(null);

        Search.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        Search.setText("Search recipes by name or ID");
        Search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchActionPerformed(evt);
            }
        });
        jPanel7.add(Search);
        Search.setBounds(10, 10, 270, 30);

        ADD7.setBackground(new java.awt.Color(255, 255, 255));
        ADD7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ADD7.setText("Refresh");
        ADD7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ADD7ActionPerformed(evt);
            }
        });
        jPanel7.add(ADD7);
        ADD7.setBounds(380, 10, 83, 30);

        category.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "appetizers", "salads", "soups", "main dishes", "desserts", "vegetarian", "seasonal" }));
        category.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                categoryActionPerformed(evt);
            }
        });
        jPanel7.add(category);
        category.setBounds(490, 10, 90, 20);

        ADD10.setBackground(new java.awt.Color(255, 255, 255));
        ADD10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ADD10.setText("Search");
        ADD10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ADD10ActionPerformed(evt);
            }
        });
        jPanel7.add(ADD10);
        ADD10.setBounds(290, 10, 80, 30);

        jPanel8.add(jPanel7);
        jPanel7.setBounds(230, 20, 590, 50);

        jPanel5.setBackground(new java.awt.Color(0, 0, 0,60));
        jPanel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel5.setLayout(null);
        jPanel8.add(jPanel5);
        jPanel5.setBounds(230, 70, 590, 390);

        jPanel15.setBackground(new java.awt.Color(0, 0, 0,60));
        jPanel15.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel15.setLayout(null);

        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/small logo.png"))); // NOI18N
        jLabel25.setText("jLabel9");
        jPanel15.add(jLabel25);
        jLabel25.setBounds(10, 10, 140, 120);

        ADD22.setBackground(new java.awt.Color(255, 255, 255));
        ADD22.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ADD22.setText("Logout");
        ADD22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ADD22ActionPerformed(evt);
            }
        });
        jPanel15.add(ADD22);
        ADD22.setBounds(40, 390, 90, 30);

        ADD23.setBackground(new java.awt.Color(255, 255, 255));
        ADD23.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ADD23.setText("Home");
        ADD23.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ADD23MouseClicked(evt);
            }
        });
        ADD23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ADD23ActionPerformed(evt);
            }
        });
        jPanel15.add(ADD23);
        ADD23.setBounds(40, 140, 90, 30);

        ADD24.setBackground(new java.awt.Color(255, 255, 255));
        ADD24.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ADD24.setText("View");
        ADD24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ADD24ActionPerformed(evt);
            }
        });
        jPanel15.add(ADD24);
        ADD24.setBounds(40, 240, 90, 30);

        ADD25.setBackground(new java.awt.Color(255, 255, 255));
        ADD25.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ADD25.setText("Share");
        ADD25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ADD25ActionPerformed(evt);
            }
        });
        jPanel15.add(ADD25);
        ADD25.setBounds(40, 290, 90, 30);

        ADD26.setBackground(new java.awt.Color(255, 255, 255));
        ADD26.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ADD26.setText("Profile");
        ADD26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ADD26ActionPerformed(evt);
            }
        });
        jPanel15.add(ADD26);
        ADD26.setBounds(40, 340, 90, 30);

        ADD27.setBackground(new java.awt.Color(255, 255, 255));
        ADD27.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ADD27.setText("Manage");
        ADD27.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ADD27MouseClicked(evt);
            }
        });
        ADD27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ADD27ActionPerformed(evt);
            }
        });
        jPanel15.add(ADD27);
        ADD27.setBounds(40, 190, 90, 30);

        jPanel8.add(jPanel15);
        jPanel15.setBounds(20, 20, 180, 440);

        jPanel2.add(jPanel8);
        jPanel8.setBounds(20, 60, 840, 480);

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/new back.png"))); // NOI18N
        jLabel12.setText("jLabel12");
        jPanel2.add(jLabel12);
        jLabel12.setBounds(0, -10, 880, 590);

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 880, 570));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        homePage2 l = new homePage2();
        l.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel4MouseClicked

    private void ADD7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ADD7ActionPerformed
        Search.setText("");
        if (category.getItemCount() > 0) {
            category.setSelectedIndex(0);
        }
    }//GEN-LAST:event_ADD7ActionPerformed

    private void categoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_categoryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_categoryActionPerformed

    private void SearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SearchActionPerformed

    private void ADD10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ADD10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ADD10ActionPerformed

    private void ADD22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ADD22ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ADD22ActionPerformed

    private void ADD23MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ADD23MouseClicked
        homePage2 l = new homePage2();
        l.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ADD23MouseClicked

    private void ADD23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ADD23ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ADD23ActionPerformed

    private void ADD24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ADD24ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ADD24ActionPerformed

    private void ADD25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ADD25ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ADD25ActionPerformed

    private void ADD26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ADD26ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ADD26ActionPerformed

    private void ADD27MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ADD27MouseClicked
Manage l = new Manage();
        l.setVisible(true);
        this.dispose();         // TODO add your handling code here:
    }//GEN-LAST:event_ADD27MouseClicked

    private void ADD27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ADD27ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ADD27ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(homePage2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(homePage2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(homePage2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(homePage2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new homePage2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ADD10;
    private javax.swing.JButton ADD22;
    private javax.swing.JButton ADD23;
    private javax.swing.JButton ADD24;
    private javax.swing.JButton ADD25;
    private javax.swing.JButton ADD26;
    private javax.swing.JButton ADD27;
    private javax.swing.JButton ADD7;
    private javax.swing.JTextField Search;
    private java.awt.Canvas canvas1;
    private javax.swing.JComboBox<String> category;
    private java.awt.Choice choice1;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JDialog jDialog2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSpinner jSpinner1;
    // End of variables declaration//GEN-END:variables
}
