/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dishcovery;
import config.config;
import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public class Manage extends javax.swing.JFrame {
    private final config con = new config();

    /**
     * Creates new form homePage2
     */
    public Manage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSpinner1 = new javax.swing.JSpinner();
        jPanel6 = new javax.swing.JPanel();
        jDialog1 = new javax.swing.JDialog();
        choice1 = new java.awt.Choice();
        canvas1 = new java.awt.Canvas();
        jDialog2 = new javax.swing.JDialog();
        jFrame1 = new javax.swing.JFrame();
        jLabel23 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        Search = new javax.swing.JTextField();
        ADD13 = new javax.swing.JButton();
        category1 = new javax.swing.JComboBox<>();
        ADD14 = new javax.swing.JButton();
        jPanel10 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        ADD15 = new javax.swing.JButton();
        ADD16 = new javax.swing.JButton();
        ADD17 = new javax.swing.JButton();
        ADD18 = new javax.swing.JButton();
        ADD19 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        ADD3 = new javax.swing.JButton();
        category = new javax.swing.JComboBox<>();
        ADD8 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        ADD9 = new javax.swing.JButton();
        ADD10 = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        ADD7 = new javax.swing.JButton();
        ADD11 = new javax.swing.JButton();
        ADD12 = new javax.swing.JButton();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jPanel17 = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        ADD35 = new javax.swing.JButton();
        ADD36 = new javax.swing.JButton();
        ADD37 = new javax.swing.JButton();
        ADD38 = new javax.swing.JButton();
        ADD39 = new javax.swing.JButton();
        jLabel24 = new javax.swing.JLabel();

        jPanel6.setBackground(new java.awt.Color(0, 0, 0,80));

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/new back.png"))); // NOI18N
        jLabel23.setText("jLabel12");

        jPanel9.setBackground(new java.awt.Color(0, 0, 0,50));
        jPanel9.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel9.setLayout(null);

        jPanel7.setBackground(new java.awt.Color(0, 0, 0,60));
        jPanel7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel7.setLayout(null);

        Search.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        Search.setText("Search recipes by name or ID");
        Search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchActionPerformed(evt);
            }
        });
        jPanel7.add(Search);
        Search.setBounds(10, 10, 270, 30);

        ADD13.setBackground(new java.awt.Color(255, 255, 255));
        ADD13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ADD13.setText("Refresh");
        ADD13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ADD13ActionPerformed(evt);
            }
        });
        jPanel7.add(ADD13);
        ADD13.setBounds(390, 10, 100, 30);

        category1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "appetizers", "salads", "soups", "main dishes", "desserts", "vegetarian", "seasonal" }));
        category1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                category1ActionPerformed(evt);
            }
        });
        jPanel7.add(category1);
        category1.setBounds(500, 10, 80, 20);

        ADD14.setBackground(new java.awt.Color(255, 255, 255));
        ADD14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ADD14.setText("Search");
        ADD14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ADD14ActionPerformed(evt);
            }
        });
        jPanel7.add(ADD14);
        ADD14.setBounds(290, 10, 90, 30);

        jPanel9.add(jPanel7);
        jPanel7.setBounds(230, 20, 590, 50);

        jPanel10.setBackground(new java.awt.Color(0, 0, 0,60));
        jPanel10.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel10.setLayout(null);
        jPanel9.add(jPanel10);
        jPanel10.setBounds(230, 70, 590, 390);

        jPanel11.setBackground(new java.awt.Color(0, 0, 0,60));
        jPanel11.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel11.setLayout(null);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/small logo.png"))); // NOI18N
        jLabel10.setText("jLabel9");
        jPanel11.add(jLabel10);
        jLabel10.setBounds(10, 20, 140, 120);

        ADD15.setBackground(new java.awt.Color(255, 255, 255));
        ADD15.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ADD15.setText("Logout");
        ADD15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ADD15ActionPerformed(evt);
            }
        });
        jPanel11.add(ADD15);
        ADD15.setBounds(40, 350, 90, 30);

        ADD16.setBackground(new java.awt.Color(255, 255, 255));
        ADD16.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ADD16.setText("Manage");
        ADD16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ADD16ActionPerformed(evt);
            }
        });
        jPanel11.add(ADD16);
        ADD16.setBounds(40, 150, 90, 30);

        ADD17.setBackground(new java.awt.Color(255, 255, 255));
        ADD17.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ADD17.setText("View");
        ADD17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ADD17ActionPerformed(evt);
            }
        });
        jPanel11.add(ADD17);
        ADD17.setBounds(40, 200, 90, 30);

        ADD18.setBackground(new java.awt.Color(255, 255, 255));
        ADD18.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ADD18.setText("Share");
        ADD18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ADD18ActionPerformed(evt);
            }
        });
        jPanel11.add(ADD18);
        ADD18.setBounds(40, 250, 90, 30);

        ADD19.setBackground(new java.awt.Color(255, 255, 255));
        ADD19.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ADD19.setText("Profile");
        ADD19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ADD19ActionPerformed(evt);
            }
        });
        jPanel11.add(ADD19);
        ADD19.setBounds(40, 300, 90, 30);

        jPanel9.add(jPanel11);
        jPanel11.setBounds(20, 20, 180, 440);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 390, -1, -1));

        jPanel2.setLayout(null);

        jPanel12.setBackground(new java.awt.Color(0, 0, 0,100));
        jPanel12.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel12.setLayout(null);

        jTabbedPane1.setBackground(new java.awt.Color(0, 0, 0,100));
        jTabbedPane1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jPanel3.setBackground(new java.awt.Color(0, 0, 0,80));
        jPanel3.setLayout(null);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 165, 31));
        jLabel9.setText("ADD Recipe");
        jPanel3.add(jLabel9);
        jLabel9.setBounds(30, 10, 120, 20);
        jPanel3.add(jTextField1);
        jTextField1.setBounds(10, 60, 160, 20);

        jLabel11.setForeground(new java.awt.Color(255, 165, 31));
        jLabel11.setText("Title");
        jPanel3.add(jLabel11);
        jLabel11.setBounds(10, 40, 60, 20);

        jLabel13.setForeground(new java.awt.Color(255, 165, 31));
        jLabel13.setText("Description");
        jPanel3.add(jLabel13);
        jLabel13.setBounds(10, 100, 70, 20);
        jPanel3.add(jTextField3);
        jTextField3.setBounds(10, 120, 160, 30);
        jPanel3.add(jTextField4);
        jTextField4.setBounds(10, 180, 160, 30);

        jLabel15.setForeground(new java.awt.Color(255, 165, 31));
        jLabel15.setText("Instruction");
        jPanel3.add(jLabel15);
        jLabel15.setBounds(10, 160, 60, 20);

        jLabel16.setForeground(new java.awt.Color(255, 165, 31));
        jLabel16.setText("Date");
        jPanel3.add(jLabel16);
        jLabel16.setBounds(10, 220, 60, 20);
        jPanel3.add(jTextField6);
        jTextField6.setBounds(10, 240, 160, 30);

        jLabel17.setForeground(new java.awt.Color(255, 165, 31));
        jLabel17.setText("Category");
        jPanel3.add(jLabel17);
        jLabel17.setBounds(10, 280, 60, 20);

        ADD3.setBackground(new java.awt.Color(224, 196, 160));
        ADD3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ADD3.setForeground(new java.awt.Color(255, 165, 31));
        ADD3.setText("ADD");
        ADD3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ADD3ActionPerformed(evt);
            }
        });
        jPanel3.add(ADD3);
        ADD3.setBounds(30, 540, 120, 20);

        category.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "appetizers", "salads", "soups", "main dishes", "desserts", "vegetarian", "seasonal" }));
        category.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                categoryActionPerformed(evt);
            }
        });
        jPanel3.add(category);
        category.setBounds(10, 300, 160, 20);

        ADD8.setBackground(new java.awt.Color(224, 196, 160));
        ADD8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ADD8.setForeground(new java.awt.Color(255, 165, 31));
        ADD8.setText("ADD");
        ADD8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ADD8MouseClicked(evt);
            }
        });
        ADD8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ADD8ActionPerformed(evt);
            }
        });
        jPanel3.add(ADD8);
        ADD8.setBounds(40, 340, 100, 30);

        jTabbedPane1.addTab("Recipe", jPanel3);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(null);

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 165, 31));
        jLabel14.setText("ADD Ingredients");
        jPanel4.add(jLabel14);
        jLabel14.setBounds(20, 20, 150, 30);
        jPanel4.add(jTextField2);
        jTextField2.setBounds(10, 90, 160, 20);

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 165, 31));
        jLabel18.setText("Recipe ID");
        jPanel4.add(jLabel18);
        jLabel18.setBounds(10, 70, 60, 20);

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 165, 31));
        jLabel19.setText("name");
        jPanel4.add(jLabel19);
        jLabel19.setBounds(10, 130, 70, 20);
        jPanel4.add(jTextField5);
        jTextField5.setBounds(10, 150, 160, 20);
        jPanel4.add(jTextField7);
        jTextField7.setBounds(10, 210, 160, 20);

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 165, 31));
        jLabel20.setText("Quantity");
        jPanel4.add(jLabel20);
        jLabel20.setBounds(10, 190, 60, 20);

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 165, 31));
        jLabel21.setText("Unit");
        jPanel4.add(jLabel21);
        jLabel21.setBounds(10, 250, 60, 20);
        jPanel4.add(jTextField8);
        jTextField8.setBounds(10, 270, 160, 20);

        ADD9.setBackground(new java.awt.Color(224, 196, 160));
        ADD9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ADD9.setForeground(new java.awt.Color(255, 165, 31));
        ADD9.setText("ADD");
        ADD9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ADD9ActionPerformed(evt);
            }
        });
        jPanel4.add(ADD9);
        ADD9.setBounds(30, 540, 120, 20);

        ADD10.setBackground(new java.awt.Color(224, 196, 160));
        ADD10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ADD10.setForeground(new java.awt.Color(255, 165, 31));
        ADD10.setText("ADD");
        ADD10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ADD10ActionPerformed(evt);
            }
        });
        jPanel4.add(ADD10);
        ADD10.setBounds(40, 310, 100, 30);

        jTabbedPane1.addTab("Ingredients", jPanel4);

        jPanel12.add(jTabbedPane1);
        jTabbedPane1.setBounds(220, 20, 190, 470);

        jPanel8.setBackground(new java.awt.Color(0, 0, 0,80));
        jPanel8.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel8.setLayout(null);

        jLabel22.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 165, 31));
        jLabel22.setText("Manage");
        jLabel22.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel22MouseClicked(evt);
            }
        });
        jPanel8.add(jLabel22);
        jLabel22.setBounds(580, 0, 60, 30);

        ADD7.setBackground(new java.awt.Color(224, 196, 160));
        ADD7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ADD7.setForeground(new java.awt.Color(255, 165, 31));
        ADD7.setText("Delete");
        ADD7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ADD7MouseClicked(evt);
            }
        });
        ADD7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ADD7ActionPerformed(evt);
            }
        });
        jPanel8.add(ADD7);
        ADD7.setBounds(270, 10, 80, 30);

        ADD11.setBackground(new java.awt.Color(224, 196, 160));
        ADD11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ADD11.setForeground(new java.awt.Color(255, 165, 31));
        ADD11.setText("ADD");
        ADD11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ADD11MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ADD11MouseEntered(evt);
            }
        });
        ADD11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ADD11ActionPerformed(evt);
            }
        });
        jPanel8.add(ADD11);
        ADD11.setBounds(30, 10, 80, 30);

        ADD12.setBackground(new java.awt.Color(224, 196, 160));
        ADD12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ADD12.setForeground(new java.awt.Color(255, 165, 31));
        ADD12.setText("Update");
        ADD12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ADD12MouseClicked(evt);
            }
        });
        ADD12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ADD12ActionPerformed(evt);
            }
        });
        jPanel8.add(ADD12);
        ADD12.setBounds(150, 10, 90, 30);

        jPanel12.add(jPanel8);
        jPanel8.setBounds(430, 20, 370, 50);

        jTabbedPane2.setBackground(new java.awt.Color(0, 0, 0,100));
        jTabbedPane2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jPanel5.setBackground(new java.awt.Color(0, 0, 0,80));
        jPanel5.setLayout(null);

        jTable1.setBackground(new java.awt.Color(0, 0, 0,80));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Recipe ID", "Tittle", "Descrition", "date", "status", "Category"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setHeaderValue("Recipe ID");
            jTable1.getColumnModel().getColumn(1).setHeaderValue("Tittle");
            jTable1.getColumnModel().getColumn(2).setHeaderValue("Descrition");
            jTable1.getColumnModel().getColumn(3).setHeaderValue("date");
            jTable1.getColumnModel().getColumn(4).setHeaderValue("status");
            jTable1.getColumnModel().getColumn(5).setHeaderValue("Category");
        }

        jPanel5.add(jScrollPane1);
        jScrollPane1.setBounds(0, 0, 390, 350);

        jTabbedPane2.addTab("recipe", jPanel5);

        jTable3.setBackground(new java.awt.Color(0, 0, 0,80));
        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Recipe ID", "Tittle", "Descrition", "date", "status", "Category"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(jTable3);

        jTabbedPane2.addTab("Ingredients", jScrollPane4);

        jPanel12.add(jTabbedPane2);
        jTabbedPane2.setBounds(430, 90, 380, 400);

        jPanel17.setBackground(new java.awt.Color(0, 0, 0,60));
        jPanel17.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel17.setLayout(null);

        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/small logo.png"))); // NOI18N
        jLabel28.setText("jLabel9");
        jPanel17.add(jLabel28);
        jLabel28.setBounds(10, 10, 140, 120);

        ADD35.setBackground(new java.awt.Color(255, 255, 255));
        ADD35.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ADD35.setText("View");
        ADD35.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ADD35ActionPerformed(evt);
            }
        });
        jPanel17.add(ADD35);
        ADD35.setBounds(40, 270, 90, 30);

        ADD36.setBackground(new java.awt.Color(255, 255, 255));
        ADD36.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ADD36.setText("Share");
        ADD36.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ADD36ActionPerformed(evt);
            }
        });
        jPanel17.add(ADD36);
        ADD36.setBounds(40, 320, 90, 30);

        ADD37.setBackground(new java.awt.Color(255, 255, 255));
        ADD37.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ADD37.setText("Profile");
        ADD37.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ADD37ActionPerformed(evt);
            }
        });
        jPanel17.add(ADD37);
        ADD37.setBounds(40, 370, 90, 30);

        ADD38.setBackground(new java.awt.Color(255, 255, 255));
        ADD38.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ADD38.setText("Manage");
        ADD38.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ADD38MouseClicked(evt);
            }
        });
        ADD38.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ADD38ActionPerformed(evt);
            }
        });
        jPanel17.add(ADD38);
        ADD38.setBounds(40, 220, 90, 30);

        ADD39.setBackground(new java.awt.Color(255, 255, 255));
        ADD39.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ADD39.setText("Home");
        ADD39.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ADD39MouseClicked(evt);
            }
        });
        ADD39.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ADD39ActionPerformed(evt);
            }
        });
        jPanel17.add(ADD39);
        ADD39.setBounds(40, 170, 90, 30);

        jPanel12.add(jPanel17);
        jPanel17.setBounds(20, 20, 180, 470);

        jPanel2.add(jPanel12);
        jPanel12.setBounds(20, 40, 840, 510);

        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/new back.png"))); // NOI18N
        jLabel24.setText("jLabel12");
        jPanel2.add(jLabel24);
        jLabel24.setBounds(0, 10, 880, 570);

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 880, 580));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ADD3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ADD3ActionPerformed
        String title = jTextField1.getText().trim();
        String desc = jTextField3.getText().trim();
        String author = String.valueOf(category.getSelectedItem());
        if (title.isEmpty() || desc.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Title and Description are required");
            return;
        }
        con.addRecord("INSERT INTO Recipes (r_title, r_description, r_author) VALUES (?, ?, ?)", title, desc, author);
        JOptionPane.showMessageDialog(this, "Recipe added");
    }//GEN-LAST:event_ADD3ActionPerformed

    private void ADD7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ADD7ActionPerformed
        String title = jTextField1.getText().trim();
        String desc = jTextField3.getText().trim();
        String author = String.valueOf(category.getSelectedItem());
        if (title.isEmpty() || desc.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Title and Description are required");
            return;
        }
        con.addRecord("INSERT INTO Recipes (r_title, r_description, r_author) VALUES (?, ?, ?)", title, desc, author);
        JOptionPane.showMessageDialog(this, "Recipe added");
    }//GEN-LAST:event_ADD7ActionPerformed

    private void categoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_categoryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_categoryActionPerformed

    private void ADD9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ADD9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ADD9ActionPerformed

    private void ADD10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ADD10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ADD10ActionPerformed

    private void ADD8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ADD8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ADD8ActionPerformed

    private void ADD11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ADD11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ADD11ActionPerformed

    private void ADD12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ADD12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ADD12ActionPerformed

    private void SearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SearchActionPerformed

    private void ADD13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ADD13ActionPerformed
        Search.setText("");
        if (category.getItemCount() > 0) {
            category.setSelectedIndex(0);
        }
    }//GEN-LAST:event_ADD13ActionPerformed

    private void category1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_category1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_category1ActionPerformed

    private void ADD14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ADD14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ADD14ActionPerformed

    private void ADD15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ADD15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ADD15ActionPerformed

    private void ADD16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ADD16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ADD16ActionPerformed

    private void ADD17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ADD17ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ADD17ActionPerformed

    private void ADD18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ADD18ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ADD18ActionPerformed

    private void ADD19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ADD19ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ADD19ActionPerformed

    private void ADD11MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ADD11MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_ADD11MouseEntered

    private void ADD11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ADD11MouseClicked
Manage l = new Manage();
        l.setVisible(true);
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_ADD11MouseClicked

    private void ADD12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ADD12MouseClicked
Update l = new Update();
        l.setVisible(true);
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_ADD12MouseClicked

    private void ADD7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ADD7MouseClicked
Delete l = new Delete();
        l.setVisible(true);
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_ADD7MouseClicked

    private void ADD8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ADD8MouseClicked
   
    }//GEN-LAST:event_ADD8MouseClicked

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable1MouseClicked

    private void ADD30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ADD30ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ADD30ActionPerformed

    private void ADD31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ADD31ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ADD31ActionPerformed

    private void ADD32ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ADD32ActionPerformed
        profile l = new profile();
        l.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ADD32ActionPerformed

    private void ADD33MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ADD33MouseClicked
        Manage l = new Manage();
        l.setVisible(true);
        this.dispose();         // TODO add your handling code here:
    }//GEN-LAST:event_ADD33MouseClicked

    private void ADD33ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ADD33ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ADD33ActionPerformed

    private void ADD34MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ADD34MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_ADD34MouseClicked

    private void ADD34ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ADD34ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ADD34ActionPerformed

    private void ADD35ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ADD35ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ADD35ActionPerformed

    private void ADD36ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ADD36ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ADD36ActionPerformed

    private void ADD37ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ADD37ActionPerformed
        profile l = new profile();
        l.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ADD37ActionPerformed

    private void ADD38MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ADD38MouseClicked
        Manage l = new Manage();
        l.setVisible(true);
        this.dispose();         // TODO add your handling code here:
    }//GEN-LAST:event_ADD38MouseClicked

    private void ADD38ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ADD38ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ADD38ActionPerformed

    private void ADD39MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ADD39MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_ADD39MouseClicked

    private void ADD39ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ADD39ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ADD39ActionPerformed

    private void jLabel22MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel22MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel22MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Manage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Manage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Manage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Manage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Manage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ADD10;
    private javax.swing.JButton ADD11;
    private javax.swing.JButton ADD12;
    private javax.swing.JButton ADD13;
    private javax.swing.JButton ADD14;
    private javax.swing.JButton ADD15;
    private javax.swing.JButton ADD16;
    private javax.swing.JButton ADD17;
    private javax.swing.JButton ADD18;
    private javax.swing.JButton ADD19;
    private javax.swing.JButton ADD3;
    private javax.swing.JButton ADD30;
    private javax.swing.JButton ADD31;
    private javax.swing.JButton ADD32;
    private javax.swing.JButton ADD33;
    private javax.swing.JButton ADD34;
    private javax.swing.JButton ADD35;
    private javax.swing.JButton ADD36;
    private javax.swing.JButton ADD37;
    private javax.swing.JButton ADD38;
    private javax.swing.JButton ADD39;
    private javax.swing.JButton ADD7;
    private javax.swing.JButton ADD8;
    private javax.swing.JButton ADD9;
    private javax.swing.JTextField Search;
    private java.awt.Canvas canvas1;
    private javax.swing.JComboBox<String> category;
    private javax.swing.JComboBox<String> category1;
    private java.awt.Choice choice1;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JDialog jDialog2;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    // End of variables declaration//GEN-END:variables
}
