/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dishcovery;
import java.awt.Image;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public class profile extends javax.swing.JFrame {
    private Integer currentUserId = null;

    /**
     * Creates new form homePage2
     */
    public profile() {
        config.Session.requireLogin(this);
        if (!config.Session.getInstance().isLoggedIn()) {
            return;
        }
        initComponents();
        loadProfile();
        displayReviewedRecipes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSpinner1 = new javax.swing.JSpinner();
        jPanel6 = new javax.swing.JPanel();
        jDialog1 = new javax.swing.JDialog();
        choice1 = new java.awt.Choice();
        canvas1 = new java.awt.Canvas();
        jDialog2 = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        jSplitPane1 = new javax.swing.JSplitPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        profilerole = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        NoRecipes = new javax.swing.JLabel();
        profilename1 = new javax.swing.JLabel();
        profileemail1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        profile = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Recipereviewed = new javax.swing.JTable();
        jPanel18 = new javax.swing.JPanel();
        EditProfile = new javax.swing.JButton();
        ADD28 = new javax.swing.JButton();
        EditProfile1 = new javax.swing.JButton();
        View = new javax.swing.JButton();
        jPanel21 = new javax.swing.JPanel();
        ADD55 = new javax.swing.JButton();
        ADD56 = new javax.swing.JButton();
        ADD57 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        ADD59 = new javax.swing.JButton();
        Logs = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();

        jPanel6.setBackground(new java.awt.Color(0, 0, 0,80));

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 390, -1, -1));

        jPanel2.setLayout(null);

        jPanel10.setBackground(new java.awt.Color(0, 0, 0,100));
        jPanel10.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel10.setLayout(null);

        jPanel9.setBackground(new java.awt.Color(0, 0, 0,80));
        jPanel9.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel9.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Role:");
        jPanel9.add(jLabel2);
        jLabel2.setBounds(170, 110, 40, 30);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("User Name");
        jPanel9.add(jLabel3);
        jLabel3.setBounds(170, 20, 320, 30);

        profilerole.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        profilerole.setForeground(new java.awt.Color(255, 255, 255));
        profilerole.setText("Role");
        jPanel9.add(profilerole);
        profilerole.setBounds(220, 110, 60, 30);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Email:");
        jPanel9.add(jLabel5);
        jLabel5.setBounds(170, 80, 50, 30);

        NoRecipes.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        NoRecipes.setForeground(new java.awt.Color(255, 255, 255));
        NoRecipes.setText("0");
        jPanel9.add(NoRecipes);
        NoRecipes.setBounds(200, 170, 100, 30);

        profilename1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        profilename1.setForeground(new java.awt.Color(255, 255, 255));
        profilename1.setText("Name");
        jPanel9.add(profilename1);
        profilename1.setBounds(220, 50, 320, 30);

        profileemail1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        profileemail1.setForeground(new java.awt.Color(255, 255, 255));
        profileemail1.setText("email");
        jPanel9.add(profileemail1);
        profileemail1.setBounds(220, 80, 340, 30);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Name:");
        jPanel9.add(jLabel7);
        jLabel7.setBounds(170, 50, 60, 30);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("No. of Recipe reviewed:");
        jPanel9.add(jLabel8);
        jLabel8.setBounds(20, 170, 170, 30);
        jPanel9.add(profile);
        profile.setBounds(20, 20, 130, 130);

        jPanel10.add(jPanel9);
        jPanel9.setBounds(220, 20, 590, 220);

        Recipereviewed.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(Recipereviewed);

        jPanel10.add(jScrollPane1);
        jScrollPane1.setBounds(222, 240, 590, 140);

        jPanel18.setBackground(new java.awt.Color(0, 0, 0,80));
        jPanel18.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel18.setLayout(null);

        EditProfile.setBackground(new java.awt.Color(255, 255, 255));
        EditProfile.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        EditProfile.setText("Add Image");
        EditProfile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EditProfileMouseClicked(evt);
            }
        });
        EditProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditProfileActionPerformed(evt);
            }
        });
        jPanel18.add(EditProfile);
        EditProfile.setBounds(20, 10, 120, 30);

        ADD28.setBackground(new java.awt.Color(255, 255, 255));
        ADD28.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ADD28.setText("Logout");
        ADD28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ADD28ActionPerformed(evt);
            }
        });
        jPanel18.add(ADD28);
        ADD28.setBounds(450, 10, 120, 30);

        EditProfile1.setBackground(new java.awt.Color(255, 255, 255));
        EditProfile1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        EditProfile1.setText("Edit Profile");
        EditProfile1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EditProfile1MouseClicked(evt);
            }
        });
        EditProfile1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditProfile1ActionPerformed(evt);
            }
        });
        jPanel18.add(EditProfile1);
        EditProfile1.setBounds(170, 10, 120, 30);

        View.setBackground(new java.awt.Color(255, 255, 255));
        View.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        View.setText("View");
        View.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ViewMouseClicked(evt);
            }
        });
        View.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewActionPerformed(evt);
            }
        });
        jPanel18.add(View);
        View.setBounds(310, 10, 120, 30);

        jPanel10.add(jPanel18);
        jPanel18.setBounds(220, 390, 590, 50);

        jPanel21.setBackground(new java.awt.Color(0, 0, 0,60));
        jPanel21.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel21.setLayout(null);

        ADD55.setBackground(new java.awt.Color(255, 255, 255));
        ADD55.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ADD55.setText("Profile");
        ADD55.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ADD55ActionPerformed(evt);
            }
        });
        jPanel21.add(ADD55);
        ADD55.setBounds(40, 350, 100, 30);

        ADD56.setBackground(new java.awt.Color(255, 255, 255));
        ADD56.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ADD56.setText("Users");
        ADD56.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ADD56MouseClicked(evt);
            }
        });
        ADD56.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ADD56ActionPerformed(evt);
            }
        });
        jPanel21.add(ADD56);
        ADD56.setBounds(40, 170, 100, 30);

        ADD57.setBackground(new java.awt.Color(255, 255, 255));
        ADD57.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ADD57.setText("Home");
        ADD57.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ADD57MouseClicked(evt);
            }
        });
        ADD57.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ADD57ActionPerformed(evt);
            }
        });
        jPanel21.add(ADD57);
        ADD57.setBounds(40, 110, 100, 30);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("ADMIN PANEL");
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });
        jPanel21.add(jLabel9);
        jLabel9.setBounds(20, 20, 140, 40);

        ADD59.setBackground(new java.awt.Color(255, 255, 255));
        ADD59.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ADD59.setText("Review");
        ADD59.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ADD59MouseClicked(evt);
            }
        });
        ADD59.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ADD59ActionPerformed(evt);
            }
        });
        jPanel21.add(ADD59);
        ADD59.setBounds(40, 230, 100, 30);

        Logs.setBackground(new java.awt.Color(255, 255, 255));
        Logs.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Logs.setText("Logs");
        Logs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogsActionPerformed(evt);
            }
        });
        jPanel21.add(Logs);
        Logs.setBounds(40, 290, 100, 30);

        jPanel10.add(jPanel21);
        jPanel21.setBounds(20, 20, 180, 430);

        jPanel2.add(jPanel10);
        jPanel10.setBounds(20, 30, 840, 480);

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/new back.png"))); // NOI18N
        jLabel12.setText("jLabel12");
        jPanel2.add(jLabel12);
        jLabel12.setBounds(0, -10, 880, 590);

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 880, 570));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ADD55ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ADD55ActionPerformed
        profile l = new profile();
        l.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ADD55ActionPerformed

    private void ADD56MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ADD56MouseClicked
        Users l = new Users();
        l.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ADD56MouseClicked

    private void ADD56ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ADD56ActionPerformed
        Users l = new Users();
        l.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ADD56ActionPerformed

    private void ADD57MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ADD57MouseClicked
        Admin l = new Admin();
        l.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ADD57MouseClicked

    private void ADD57ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ADD57ActionPerformed
        Admin l = new Admin();
        l.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ADD57ActionPerformed

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        Admin l = new Admin();
        l.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel9MouseClicked

    private void ADD59MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ADD59MouseClicked
        review l = new review();
        l.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ADD59MouseClicked

    private void ADD59ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ADD59ActionPerformed
        review l = new review();
        l.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ADD59ActionPerformed

    private void LogsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogsActionPerformed
        Logs l = new Logs();
        l.setVisible(true);
        this.dispose();  // TODO add your handling code here:
    }//GEN-LAST:event_LogsActionPerformed

    private void loadProfile() {
        String identifier = config.Session.getInstance().getUsername();
        if (identifier == null || identifier.trim().isEmpty()) {
             return; 
        }
        config.config con = new config.config();
        con.ensureUsersTable();
        java.util.List<java.util.Map<String, Object>> rows = con.fetchRecords(
            "SELECT u_id, u_full_name, u_email, u_username, u_role, u_image FROM Users WHERE u_username = ? OR u_email = ? LIMIT 1",
            identifier, identifier
        );
        if (!rows.isEmpty()) {
            java.util.Map<String, Object> row = rows.get(0);
            try {
                Object idObj = row.get("u_id");
                if (idObj != null) {
                    currentUserId = Integer.parseInt(idObj.toString());
                }
            } catch (Exception ignore) {}
            String uname = String.valueOf(row.get("u_username"));
            String fname = String.valueOf(row.get("u_full_name"));
            String email = String.valueOf(row.get("u_email"));
            String role = String.valueOf(row.get("u_role"));
            jLabel3.setText(uname != null ? uname : "");
            profilename1.setText(fname != null ? fname : "");
            profileemail1.setText(email != null ? email : "");
            profilerole.setText(role != null ? role : "");
            
            Object imgObj = row.get("u_image");
            if (imgObj instanceof byte[]) {
                byte[] img = (byte[]) imgObj;
                if (img != null && img.length > 0) {
                    javax.swing.ImageIcon icon = new javax.swing.ImageIcon(img);
                    java.awt.Image im = icon.getImage();
                    java.awt.Image myImg = im.getScaledInstance(profile.getWidth(), profile.getHeight(), java.awt.Image.SCALE_SMOOTH);
                    profile.setIcon(new javax.swing.ImageIcon(myImg));
                }
            }

            con.ensureRecipesTable();
            double cnt = con.getSingleValue("SELECT COUNT(*) FROM Recipes WHERE r_reviewed_by = ?", uname);
            NoRecipes.setText(String.valueOf((int) cnt));
        }
    }

    private void ADD28ActionPerformed(java.awt.event.ActionEvent evt) {
        config.Session.logout(this);
    }

    private void EditProfileMouseClicked(java.awt.event.MouseEvent evt) {
        EditProfileActionPerformed(null);
    }

    private void EditProfileActionPerformed(java.awt.event.ActionEvent evt) {
        JFileChooser chooser = new JFileChooser();
        chooser.setFileFilter(new javax.swing.filechooser.FileNameExtensionFilter("Images", "jpg", "jpeg", "png", "gif"));
        int result = chooser.showOpenDialog(null);
        if (result == JFileChooser.APPROVE_OPTION) {
            File f = chooser.getSelectedFile();
            String path = f.getAbsolutePath();
            try {
                File image = new File(path);
                byte[] user_image;
                try (FileInputStream fis = new FileInputStream(image);
                     ByteArrayOutputStream bos = new ByteArrayOutputStream()) {
                    byte[] buf = new byte[1024];
                    for (int readNum; (readNum = fis.read(buf)) != -1;) {
                        bos.write(buf, 0, readNum);
                    }
                    user_image = bos.toByteArray();
                }

                ImageIcon imageIcon = new ImageIcon(new ImageIcon(path).getImage().getScaledInstance(profile.getWidth(), profile.getHeight(), Image.SCALE_SMOOTH));
                profile.setIcon(imageIcon);

                config.config con = new config.config();
                String username = config.Session.getInstance().getUsername();
                if (username == null || username.trim().isEmpty()) {
                    JOptionPane.showMessageDialog(null, "Unable to locate current user.");
                    return;
                }
                con.updateRecord("UPDATE Users SET u_image = ? WHERE u_username = ?", user_image, username);
                JOptionPane.showMessageDialog(null, "Profile Image Updated Successfully");
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Error processing image: " + e.getMessage());
            }
        }
    }

    private void EditProfile1MouseClicked(java.awt.event.MouseEvent evt) {
        EditProfile1ActionPerformed(null);
    }

    private void EditProfile1ActionPerformed(java.awt.event.ActionEvent evt) {
        if (currentUserId == null) {
            int sid = config.Session.getInstance().getId();
            if (sid > 0) {
                currentUserId = sid;
            }
        }
        if (currentUserId == null) {
            String identifier = config.Session.getInstance().getUsername();
            if (identifier == null || identifier.trim().isEmpty()) {
                identifier = jLabel3.getText();
            }
            if (identifier == null || identifier.trim().isEmpty()) {
                identifier = profileemail1.getText();
            }
            if (identifier != null && !identifier.trim().isEmpty()) {
                config.config con = new config.config();
                con.ensureUsersTable();
                java.util.List<java.util.Map<String, Object>> rows = con.fetchRecords(
                    "SELECT u_id FROM Users WHERE u_username = ? OR u_email = ? LIMIT 1",
                    identifier, identifier
                );
                if (!rows.isEmpty()) {
                    try {
                        currentUserId = Integer.parseInt(String.valueOf(rows.get(0).get("u_id")));
                    } catch (Exception ignore) {}
                }
            }
        }
        if (currentUserId == null) {
            String name = profilename1.getText() != null ? profilename1.getText().trim() : "";
            String email = profileemail1.getText() != null ? profileemail1.getText().trim() : "";
            String role = profilerole.getText() != null ? profilerole.getText().trim() : "";
            String uname = jLabel3.getText() != null ? jLabel3.getText().trim() : "";
            if ((!name.isEmpty() && !email.isEmpty() && !role.isEmpty()) || !uname.isEmpty()) {
                config.config con = new config.config();
                con.ensureUsersTable();
                java.util.List<java.util.Map<String, Object>> rows = con.fetchRecords(
                    "SELECT u_id FROM Users WHERE (u_full_name = ? AND u_email = ? AND u_role = ?) OR (u_username = ? OR u_email = ?) LIMIT 1",
                    name, email, role, uname, email
                );
                if (!rows.isEmpty()) {
                    try {
                        currentUserId = Integer.parseInt(String.valueOf(rows.get(0).get("u_id")));
                    } catch (Exception ignore) {}
                }
            }
        }
        if (currentUserId != null) {
            openUserEditor(currentUserId);
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Unable to locate current user.");
        }
    }

    private void openUserEditor(int userId) {
        try {
            ADDuser uform = new ADDuser();
            uform.loadUser(userId);
            uform.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosed(java.awt.event.WindowEvent e) {
                    loadProfile();
                }
            });
            uform.setVisible(true);
        } catch (Throwable ex) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error opening user editor: " + ex.getMessage());
        }
    }

    private void displayReviewedRecipes() {
        String uname = config.Session.getInstance().getUsername();
        if (uname == null) return;
        config.config con = new config.config();
        con.ensureRecipesTable();
        String sql = "SELECT r_id AS ID, r_title AS Title, r_author AS Author, r_category AS Category, r_date AS Date, r_status AS Status FROM Recipes WHERE r_reviewed_by = ?";
        con.displayData(sql, Recipereviewed, uname);
    }

    private void ViewMouseClicked(java.awt.event.MouseEvent evt) {
        ViewActionPerformed(null);
    }

    private void ViewActionPerformed(java.awt.event.ActionEvent evt) {
        int row = Recipereviewed.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Please select a recipe to view.");
            return;
        }
        String idStr = String.valueOf(Recipereviewed.getValueAt(row, 0));
        View11.openFrom(this, idStr, null, null);
    }

    private void ADD35ActionPerformed(java.awt.event.ActionEvent evt) {
        if ("Admin".equalsIgnoreCase(config.Session.getInstance().getRole())) {
        } else {
            JOptionPane.showMessageDialog(this, "Access Denied: Only Admins can access Approve.");
        }
    }

    private void ADD37ActionPerformed(java.awt.event.ActionEvent evt) {
        if ("Admin".equalsIgnoreCase(config.Session.getInstance().getRole())) {
            profile l = new profile();
            l.setVisible(true);
            this.dispose();
        }
    }

    private void ADD38MouseClicked(java.awt.event.MouseEvent evt) {
        Manage l = new Manage();
        l.setVisible(true);
        this.dispose();
    }

    private void ADD38ActionPerformed(java.awt.event.ActionEvent evt) {
        Users l = new Users();
        l.setVisible(true);
        this.dispose();
    }

    private void ADD39MouseClicked(java.awt.event.MouseEvent evt) {
    }

    private void ADD39ActionPerformed(java.awt.event.ActionEvent evt) {
        homePage2 l = new homePage2();
        l.setVisible(true);
        this.dispose();
    }

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {
        if ("Admin".equalsIgnoreCase(config.Session.getInstance().getRole())) {
            review l = new review();
            l.setVisible(true);
            this.dispose();
        } else {
            homePage2 l = new homePage2();
            l.setVisible(true);
            this.dispose();
        }
    }

    private void ADD40MouseClicked(java.awt.event.MouseEvent evt) {
    }

    private void ADD40ActionPerformed(java.awt.event.ActionEvent evt) {
        review l = new review();
        l.setVisible(true);
        this.dispose();
    }

    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                if (config.Session.getInstance().isLoggedIn()) {
                    new profile().setVisible(true);
                } else {
                    new landingPage1().setVisible(true);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ADD28;
    private javax.swing.JButton ADD55;
    private javax.swing.JButton ADD56;
    private javax.swing.JButton ADD57;
    private javax.swing.JButton ADD59;
    private javax.swing.JButton EditProfile;
    private javax.swing.JButton EditProfile1;
    private javax.swing.JButton Logs;
    private javax.swing.JLabel NoRecipes;
    private javax.swing.JTable Recipereviewed;
    private javax.swing.JButton View;
    private java.awt.Canvas canvas1;
    private java.awt.Choice choice1;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JDialog jDialog2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JLabel profile;
    private javax.swing.JLabel profileemail1;
    private javax.swing.JLabel profilename1;
    private javax.swing.JLabel profilerole;
    // End of variables declaration//GEN-END:variables
}
