/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dishcovery;

/**
 *
 * @author user
 */
public class profileadmin extends javax.swing.JFrame {

    /**
     * Creates new form homePage2
     */
    public profileadmin() {
        config.Session.requireLogin(this);
        initComponents();
        loadProfile();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSpinner1 = new javax.swing.JSpinner();
        jPanel6 = new javax.swing.JPanel();
        jDialog1 = new javax.swing.JDialog();
        choice1 = new java.awt.Choice();
        canvas1 = new java.awt.Canvas();
        jDialog2 = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        jSplitPane1 = new javax.swing.JSplitPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        profileimage = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        profilerole = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        NoRecipes = new javax.swing.JLabel();
        profilename1 = new javax.swing.JLabel();
        profileemail1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel18 = new javax.swing.JPanel();
        EditProfile = new javax.swing.JButton();
        ADD28 = new javax.swing.JButton();
        EditProfile1 = new javax.swing.JButton();
        jPanel17 = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        ADD35 = new javax.swing.JButton();
        ADD36 = new javax.swing.JButton();
        ADD37 = new javax.swing.JButton();
        ADD38 = new javax.swing.JButton();
        ADD39 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();

        jPanel6.setBackground(new java.awt.Color(0, 0, 0,80));

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 390, -1, -1));

        jPanel2.setLayout(null);

        jPanel10.setBackground(new java.awt.Color(0, 0, 0,100));
        jPanel10.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel10.setLayout(null);

        jPanel9.setBackground(new java.awt.Color(0, 0, 0,80));
        jPanel9.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel9.setLayout(null);

        profileimage.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9.add(profileimage);
        profileimage.setBounds(20, 20, 120, 120);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Role:");
        jPanel9.add(jLabel2);
        jLabel2.setBounds(170, 110, 40, 30);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("User Name");
        jPanel9.add(jLabel3);
        jLabel3.setBounds(170, 20, 320, 30);

        profilerole.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        profilerole.setForeground(new java.awt.Color(255, 255, 255));
        profilerole.setText("Role");
        jPanel9.add(profilerole);
        profilerole.setBounds(220, 110, 60, 30);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Email:");
        jPanel9.add(jLabel5);
        jLabel5.setBounds(170, 80, 50, 30);

        NoRecipes.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        NoRecipes.setForeground(new java.awt.Color(255, 255, 255));
        NoRecipes.setText("0");
        jPanel9.add(NoRecipes);
        NoRecipes.setBounds(130, 170, 100, 30);

        profilename1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        profilename1.setForeground(new java.awt.Color(255, 255, 255));
        profilename1.setText("Name");
        jPanel9.add(profilename1);
        profilename1.setBounds(220, 50, 320, 30);

        profileemail1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        profileemail1.setForeground(new java.awt.Color(255, 255, 255));
        profileemail1.setText("email");
        jPanel9.add(profileemail1);
        profileemail1.setBounds(220, 80, 340, 30);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Name:");
        jPanel9.add(jLabel7);
        jLabel7.setBounds(170, 50, 60, 30);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("No. of Recipe:");
        jPanel9.add(jLabel8);
        jLabel8.setBounds(20, 170, 100, 30);

        jPanel10.add(jPanel9);
        jPanel9.setBounds(220, 20, 590, 220);

        jPanel18.setBackground(new java.awt.Color(0, 0, 0,80));
        jPanel18.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel18.setLayout(null);

        EditProfile.setBackground(new java.awt.Color(255, 255, 255));
        EditProfile.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        EditProfile.setText("Add Image");
        EditProfile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EditProfileMouseClicked(evt);
            }
        });
        EditProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditProfileActionPerformed(evt);
            }
        });
        jPanel18.add(EditProfile);
        EditProfile.setBounds(40, 10, 120, 30);

        ADD28.setBackground(new java.awt.Color(255, 255, 255));
        ADD28.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ADD28.setText("Logout");
        ADD28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ADD28ActionPerformed(evt);
            }
        });
        jPanel18.add(ADD28);
        ADD28.setBounds(430, 10, 120, 30);

        EditProfile1.setBackground(new java.awt.Color(255, 255, 255));
        EditProfile1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        EditProfile1.setText("Edit Profile");
        EditProfile1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EditProfile1MouseClicked(evt);
            }
        });
        EditProfile1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditProfile1ActionPerformed(evt);
            }
        });
        jPanel18.add(EditProfile1);
        EditProfile1.setBounds(230, 10, 120, 30);

        jPanel10.add(jPanel18);
        jPanel18.setBounds(220, 250, 590, 50);

        jPanel17.setBackground(new java.awt.Color(0, 0, 0,60));
        jPanel17.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel17.setLayout(null);

        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/small logo.png"))); // NOI18N
        jLabel28.setText("jLabel9");
        jPanel17.add(jLabel28);
        jLabel28.setBounds(10, 10, 140, 120);

        ADD35.setBackground(new java.awt.Color(255, 255, 255));
        ADD35.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ADD35.setText("View");
        ADD35.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ADD35ActionPerformed(evt);
            }
        });
        jPanel17.add(ADD35);
        ADD35.setBounds(40, 270, 90, 30);

        ADD36.setBackground(new java.awt.Color(255, 255, 255));
        ADD36.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ADD36.setText("Share");
        ADD36.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ADD36ActionPerformed(evt);
            }
        });
        jPanel17.add(ADD36);
        ADD36.setBounds(40, 320, 90, 30);

        ADD37.setBackground(new java.awt.Color(255, 255, 255));
        ADD37.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ADD37.setText("Profile");
        ADD37.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ADD37ActionPerformed(evt);
            }
        });
        jPanel17.add(ADD37);
        ADD37.setBounds(40, 370, 90, 30);

        ADD38.setBackground(new java.awt.Color(255, 255, 255));
        ADD38.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ADD38.setText("Manage");
        ADD38.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ADD38MouseClicked(evt);
            }
        });
        ADD38.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ADD38ActionPerformed(evt);
            }
        });
        jPanel17.add(ADD38);
        ADD38.setBounds(40, 220, 90, 30);

        ADD39.setBackground(new java.awt.Color(255, 255, 255));
        ADD39.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ADD39.setText("Home");
        ADD39.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ADD39MouseClicked(evt);
            }
        });
        ADD39.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ADD39ActionPerformed(evt);
            }
        });
        jPanel17.add(ADD39);
        ADD39.setBounds(40, 170, 90, 30);

        jPanel10.add(jPanel17);
        jPanel17.setBounds(20, 20, 180, 470);

        jPanel2.add(jPanel10);
        jPanel10.setBounds(20, 30, 840, 510);

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/new back.png"))); // NOI18N
        jLabel12.setText("jLabel12");
        jPanel2.add(jLabel12);
        jLabel12.setBounds(0, -10, 880, 590);

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 880, 570));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void loadProfile() {
        String identifier = config.Session.getInstance().getUsername();
        if (identifier == null || identifier.trim().isEmpty()) {
            return;
        }
        config.config con = new config.config();
        con.ensureUsersTable();
        java.util.List<java.util.Map<String, Object>> rows = con.fetchRecords(
            "SELECT u_id, u_full_name, u_email, u_username, u_role FROM Users WHERE u_username = ? OR u_email = ? LIMIT 1",
            identifier, identifier
        );
        if (!rows.isEmpty()) {
            java.util.Map<String, Object> row = rows.get(0);
            String uname = String.valueOf(row.get("u_username"));
            String fname = String.valueOf(row.get("u_full_name"));
            String email = String.valueOf(row.get("u_email"));
            String role = String.valueOf(row.get("u_role"));
            jLabel3.setText(uname != null ? uname : "");
            profilename1.setText(fname != null ? fname : "");
            profileemail1.setText(email != null ? email : "");
            profilerole.setText(role != null ? role : "");
            con.ensureRecipesTable();
            double cnt = con.getSingleValue("SELECT COUNT(*) FROM Recipes WHERE r_author = ?", uname);
            NoRecipes.setText(String.valueOf((int) cnt));
        }
    }

    private void ADD28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ADD28ActionPerformed
        config.Session.getInstance().clear();
        login l = new login();
        l.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ADD28ActionPerformed

    private void EditProfileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EditProfileMouseClicked
        homePage2 l = new homePage2();
        l.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_EditProfileMouseClicked

    private void EditProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditProfileActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EditProfileActionPerformed

    private void EditProfile1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EditProfile1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_EditProfile1MouseClicked

    private void EditProfile1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditProfile1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EditProfile1ActionPerformed

    private void ADD35ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ADD35ActionPerformed
        View v = new View();
        v.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ADD35ActionPerformed

    private void ADD36ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ADD36ActionPerformed
        share p = new share();
        p.setVisible(true);
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_ADD36ActionPerformed

    private void ADD37ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ADD37ActionPerformed
        profileadmin p = new profileadmin();
        p.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ADD37ActionPerformed

    private void ADD38MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ADD38MouseClicked
        displayRecipes();
    }//GEN-LAST:event_ADD38MouseClicked

    private void ADD38ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ADD38ActionPerformed
        Manage p = new Manage();
        p.setVisible(true);
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_ADD38ActionPerformed

    private void ADD39MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ADD39MouseClicked
        homePage2 h = new homePage2();
        h.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ADD39MouseClicked

    private void ADD39ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ADD39ActionPerformed
        homePage2 p = new homePage2();
        p.setVisible(true);
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_ADD39ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(profileadmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(profileadmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(profileadmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(profileadmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new profileadmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ADD28;
    private javax.swing.JButton ADD35;
    private javax.swing.JButton ADD36;
    private javax.swing.JButton ADD37;
    private javax.swing.JButton ADD38;
    private javax.swing.JButton ADD39;
    private javax.swing.JButton EditProfile;
    private javax.swing.JButton EditProfile1;
    private javax.swing.JLabel NoRecipes;
    private java.awt.Canvas canvas1;
    private java.awt.Choice choice1;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JDialog jDialog2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JLabel profileemail1;
    private javax.swing.JPanel profileimage;
    private javax.swing.JLabel profilename1;
    private javax.swing.JLabel profilerole;
    // End of variables declaration//GEN-END:variables
}
