/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dishcovery;
import java.awt.Image;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public class profileadmin extends javax.swing.JFrame {
    private Integer currentUserId = null;
    private final config.config con = new config.config();

    /**
     * Creates new form homePage2
     */
    public profileadmin() {
        config.Session.requireLogin(this);
        if (!config.Session.getInstance().isLoggedIn()) {
            return;
        }
        initComponents();
        con.ensureFollowersTable();
        loadProfile();
        displayRecipes();
        updateFollowerCount();
    }

    private void updateFollowerCount() {
        int userId = config.Session.getInstance().getId();
        if (userId <= 0) return;
        
        double count = con.getSingleValue("SELECT COUNT(*) FROM Followers WHERE f_following_id = ?", userId);
        Followers.setText(String.valueOf((int)count));
        
        double followingCount = con.getSingleValue("SELECT COUNT(*) FROM Followers WHERE f_follower_id = ?", userId);
        folowing.setText(String.valueOf((int)followingCount));
    }

    private void displayRecipes() {
        String username = config.Session.getInstance().getUsername();
        if (username == null) return;

        con.ensureRatingsTable();
        String sql =
                "SELECT r.r_id AS ID, " +
                "       r.r_title AS Title, " +
                "       r.r_category AS Category, " +
                "       r.r_status AS Status, " +
                "       IFNULL(ROUND(AVG(rt.r_rating), 1), 0) AS Rating " +
                "FROM Recipes r " +
                "LEFT JOIN Ratings rt ON rt.r_recipe_id = r.r_id " +
                "WHERE r.r_author = ? AND r.r_status = 'Approve' " +
                "GROUP BY r.r_id, r.r_title, r.r_category, r.r_status " +
                "ORDER BY r.r_id DESC";
        con.displayData(sql, sharedRecipeOFUser, username);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSpinner1 = new javax.swing.JSpinner();
        jPanel6 = new javax.swing.JPanel();
        jDialog1 = new javax.swing.JDialog();
        choice1 = new java.awt.Choice();
        canvas1 = new java.awt.Canvas();
        jDialog2 = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        jSplitPane1 = new javax.swing.JSplitPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        NoRecipes = new javax.swing.JLabel();
        profilename1 = new javax.swing.JLabel();
        profileemail1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        profile = new javax.swing.JLabel();
        folowers = new javax.swing.JLabel();
        Followers = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        folowing = new javax.swing.JLabel();
        jPanel18 = new javax.swing.JPanel();
        EditProfile = new javax.swing.JButton();
        ADD28 = new javax.swing.JButton();
        EditProfile1 = new javax.swing.JButton();
        View = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        sharedRecipeOFUser = new javax.swing.JTable();
        jPanel17 = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        ADD35 = new javax.swing.JButton();
        ADD36 = new javax.swing.JButton();
        ADD37 = new javax.swing.JButton();
        ADD38 = new javax.swing.JButton();
        ADD39 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();

        jPanel6.setBackground(new java.awt.Color(0, 0, 0,80));

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 390, -1, -1));

        jPanel2.setLayout(null);

        jPanel10.setBackground(new java.awt.Color(0, 0, 0,100));
        jPanel10.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel10.setLayout(null);

        jPanel9.setBackground(new java.awt.Color(0, 0, 0,80));
        jPanel9.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel9.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("User Name");
        jPanel9.add(jLabel3);
        jLabel3.setBounds(170, 20, 320, 30);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Email:");
        jPanel9.add(jLabel5);
        jLabel5.setBounds(170, 80, 50, 30);

        NoRecipes.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        NoRecipes.setForeground(new java.awt.Color(255, 255, 255));
        NoRecipes.setText("0");
        jPanel9.add(NoRecipes);
        NoRecipes.setBounds(130, 170, 100, 30);

        profilename1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        profilename1.setForeground(new java.awt.Color(255, 255, 255));
        profilename1.setText("Name");
        jPanel9.add(profilename1);
        profilename1.setBounds(220, 50, 320, 30);

        profileemail1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        profileemail1.setForeground(new java.awt.Color(255, 255, 255));
        profileemail1.setText("email");
        jPanel9.add(profileemail1);
        profileemail1.setBounds(220, 80, 340, 30);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Name:");
        jPanel9.add(jLabel7);
        jLabel7.setBounds(170, 50, 60, 30);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("No. of Recipe:");
        jPanel9.add(jLabel8);
        jLabel8.setBounds(20, 170, 100, 30);
        jPanel9.add(profile);
        profile.setBounds(20, 20, 140, 140);

        folowers.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        folowers.setForeground(new java.awt.Color(255, 255, 255));
        folowers.setText("followers:");
        jPanel9.add(folowers);
        folowers.setBounds(170, 110, 70, 30);

        Followers.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Followers.setForeground(new java.awt.Color(255, 255, 255));
        Followers.setText("followers");
        jPanel9.add(Followers);
        Followers.setBounds(250, 110, 90, 30);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("following:");
        jPanel9.add(jLabel4);
        jLabel4.setBounds(170, 140, 70, 30);

        folowing.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        folowing.setForeground(new java.awt.Color(255, 255, 255));
        folowing.setText("following");
        jPanel9.add(folowing);
        folowing.setBounds(250, 140, 100, 30);

        jPanel10.add(jPanel9);
        jPanel9.setBounds(220, 20, 590, 210);

        jPanel18.setBackground(new java.awt.Color(0, 0, 0,80));
        jPanel18.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel18.setLayout(null);

        EditProfile.setBackground(new java.awt.Color(255, 255, 255));
        EditProfile.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        EditProfile.setText("Add Image");
        EditProfile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EditProfileMouseClicked(evt);
            }
        });
        EditProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditProfileActionPerformed(evt);
            }
        });
        jPanel18.add(EditProfile);
        EditProfile.setBounds(20, 10, 120, 30);

        ADD28.setBackground(new java.awt.Color(255, 255, 255));
        ADD28.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ADD28.setText("Logout");
        ADD28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ADD28ActionPerformed(evt);
            }
        });
        jPanel18.add(ADD28);
        ADD28.setBounds(450, 10, 120, 30);

        EditProfile1.setBackground(new java.awt.Color(255, 255, 255));
        EditProfile1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        EditProfile1.setText("Edit Profile");
        EditProfile1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EditProfile1MouseClicked(evt);
            }
        });
        EditProfile1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditProfile1ActionPerformed(evt);
            }
        });
        jPanel18.add(EditProfile1);
        EditProfile1.setBounds(170, 10, 120, 30);

        View.setBackground(new java.awt.Color(255, 255, 255));
        View.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        View.setText("View");
        View.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ViewMouseClicked(evt);
            }
        });
        View.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewActionPerformed(evt);
            }
        });
        jPanel18.add(View);
        View.setBounds(310, 10, 120, 30);

        jPanel10.add(jPanel18);
        jPanel18.setBounds(220, 440, 590, 50);

        jPanel1.setLayout(null);

        sharedRecipeOFUser.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(sharedRecipeOFUser);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(1, -3, 590, 200);

        jPanel10.add(jPanel1);
        jPanel1.setBounds(220, 230, 590, 200);

        jPanel17.setBackground(new java.awt.Color(0, 0, 0,60));
        jPanel17.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel17.setLayout(null);

        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/small logo.png"))); // NOI18N
        jLabel28.setText("jLabel9");
        jPanel17.add(jLabel28);
        jLabel28.setBounds(10, 10, 140, 120);

        ADD35.setBackground(new java.awt.Color(255, 255, 255));
        ADD35.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ADD35.setText("View");
        ADD35.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ADD35ActionPerformed(evt);
            }
        });
        jPanel17.add(ADD35);
        ADD35.setBounds(40, 270, 90, 30);

        ADD36.setBackground(new java.awt.Color(255, 255, 255));
        ADD36.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ADD36.setText("Share");
        ADD36.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ADD36ActionPerformed(evt);
            }
        });
        jPanel17.add(ADD36);
        ADD36.setBounds(40, 320, 90, 30);

        ADD37.setBackground(new java.awt.Color(255, 255, 255));
        ADD37.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ADD37.setText("Profile");
        ADD37.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ADD37ActionPerformed(evt);
            }
        });
        jPanel17.add(ADD37);
        ADD37.setBounds(40, 370, 90, 30);

        ADD38.setBackground(new java.awt.Color(255, 255, 255));
        ADD38.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ADD38.setText("Manage");
        ADD38.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ADD38MouseClicked(evt);
            }
        });
        ADD38.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ADD38ActionPerformed(evt);
            }
        });
        jPanel17.add(ADD38);
        ADD38.setBounds(40, 220, 90, 30);

        ADD39.setBackground(new java.awt.Color(255, 255, 255));
        ADD39.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ADD39.setText("Home");
        ADD39.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ADD39MouseClicked(evt);
            }
        });
        ADD39.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ADD39ActionPerformed(evt);
            }
        });
        jPanel17.add(ADD39);
        ADD39.setBounds(40, 170, 90, 30);

        jPanel10.add(jPanel17);
        jPanel17.setBounds(20, 20, 180, 470);

        jPanel2.add(jPanel10);
        jPanel10.setBounds(20, 30, 840, 510);

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/new back.png"))); // NOI18N
        jLabel12.setText("jLabel12");
        jPanel2.add(jLabel12);
        jLabel12.setBounds(0, -10, 880, 590);

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 880, 570));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ViewMouseClicked(java.awt.event.MouseEvent evt) {
        openSelectedRecipe();
    }

    private void ViewActionPerformed(java.awt.event.ActionEvent evt) {
        openSelectedRecipe();
    }

    private void openSelectedRecipe() {
        int row = sharedRecipeOFUser.getSelectedRow();
        if (row < 0) {
            javax.swing.JOptionPane.showMessageDialog(this, "Please select a recipe from the table to view.");
            return;
        }
        Object idObj = sharedRecipeOFUser.getValueAt(row, 0);
        if (idObj == null) {
            javax.swing.JOptionPane.showMessageDialog(this, "Please select a valid recipe.");
            return;
        }

        View11.openFrom(this, String.valueOf(idObj), config.Session.getInstance().getUsername(), null);
    }

    private void loadProfile() {
        String identifier = config.Session.getInstance().getUsername();
        if (identifier == null || identifier.trim().isEmpty()) {
             return; 
        }
        config.config con = new config.config();
        con.ensureUsersTable();
        java.util.List<java.util.Map<String, Object>> rows = con.fetchRecords(
            "SELECT u_id, u_full_name, u_email, u_username, u_role, u_image FROM Users WHERE u_username = ? OR u_email = ? LIMIT 1",
            identifier, identifier
        );
        if (!rows.isEmpty()) {
            java.util.Map<String, Object> row = rows.get(0);
            try {
                Object idObj = row.get("u_id");
                if (idObj != null) {
                    currentUserId = Integer.parseInt(idObj.toString());
                }
            } catch (Exception ignore) {}
            String uname = String.valueOf(row.get("u_username"));
            String fname = String.valueOf(row.get("u_full_name"));
            String email = String.valueOf(row.get("u_email"));
            String role = String.valueOf(row.get("u_role"));
            jLabel3.setText(uname != null ? uname : "");
            profilename1.setText(fname != null ? fname : "");
            profileemail1.setText(email != null ? email : "");
            // profilerole is used for Following count, so we don't set it to role here

            Object imgObj = row.get("u_image");
            if (imgObj instanceof byte[]) {
                byte[] img = (byte[]) imgObj;
                if (img != null && img.length > 0) {
                    javax.swing.ImageIcon icon = new javax.swing.ImageIcon(img);
                    java.awt.Image im = icon.getImage();
                    java.awt.Image myImg = im.getScaledInstance(profile.getWidth(), profile.getHeight(), java.awt.Image.SCALE_SMOOTH);
                    profile.setIcon(new javax.swing.ImageIcon(myImg));
                }
            }

            con.ensureRecipesTable();
            double cnt = con.getSingleValue("SELECT COUNT(*) FROM Recipes WHERE r_author = ? AND r_status = 'Approve'", uname);
            NoRecipes.setText(String.valueOf((int) cnt));
        }
    }

    private void ADD28ActionPerformed(java.awt.event.ActionEvent evt) {
        config.Session.logout(this);
    }

    private void EditProfileMouseClicked(java.awt.event.MouseEvent evt) {
        EditProfileActionPerformed(null);
    }

    private void EditProfileActionPerformed(java.awt.event.ActionEvent evt) {
        JFileChooser chooser = new JFileChooser();
        chooser.setFileFilter(new javax.swing.filechooser.FileNameExtensionFilter("Images", "jpg", "jpeg", "png", "gif"));
        int result = chooser.showOpenDialog(null);
        if (result == JFileChooser.APPROVE_OPTION) {
            File f = chooser.getSelectedFile();
            String path = f.getAbsolutePath();
            try {
                File image = new File(path);
                byte[] user_image;
                try (FileInputStream fis = new FileInputStream(image);
                     ByteArrayOutputStream bos = new ByteArrayOutputStream()) {
                    byte[] buf = new byte[1024];
                    for (int readNum; (readNum = fis.read(buf)) != -1;) {
                        bos.write(buf, 0, readNum);
                    }
                    user_image = bos.toByteArray();
                }

                ImageIcon imageIcon = new ImageIcon(new ImageIcon(path).getImage().getScaledInstance(profile.getWidth(), profile.getHeight(), Image.SCALE_SMOOTH));
                profile.setIcon(imageIcon);

                config.config con = new config.config();
                String username = config.Session.getInstance().getUsername();
                if (username == null || username.trim().isEmpty()) {
                    JOptionPane.showMessageDialog(null, "Unable to locate current user.");
                    return;
                }
                con.updateRecord("UPDATE Users SET u_image = ? WHERE u_username = ?", user_image, username);
                JOptionPane.showMessageDialog(null, "Profile Image Updated Successfully");
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Error processing image: " + e.getMessage());
            }
        }
    }

    private void EditProfile1MouseClicked(java.awt.event.MouseEvent evt) {
        EditProfile1ActionPerformed(null);
    }

    private void EditProfile1ActionPerformed(java.awt.event.ActionEvent evt) {
        if (currentUserId == null) {
            int sid = config.Session.getInstance().getId();
            if (sid > 0) {
                currentUserId = sid;
            }
        }
        if (currentUserId == null) {
            String identifier = config.Session.getInstance().getUsername();
            if (identifier == null || identifier.trim().isEmpty()) {
                identifier = jLabel3.getText();
            }
            if (identifier == null || identifier.trim().isEmpty()) {
                identifier = profileemail1.getText();
            }
            if (identifier != null && !identifier.trim().isEmpty()) {
                config.config con = new config.config();
                con.ensureUsersTable();
                java.util.List<java.util.Map<String, Object>> rows = con.fetchRecords(
                    "SELECT u_id FROM Users WHERE u_username = ? OR u_email = ? LIMIT 1",
                    identifier, identifier
                );
                if (!rows.isEmpty()) {
                    try {
                        currentUserId = Integer.parseInt(String.valueOf(rows.get(0).get("u_id")));
                    } catch (Exception ignore) {}
                }
            }
        }
        if (currentUserId == null) {
            String name = profilename1.getText() != null ? profilename1.getText().trim() : "";
            String email = profileemail1.getText() != null ? profileemail1.getText().trim() : "";
            String uname = jLabel3.getText() != null ? jLabel3.getText().trim() : "";
            if ((!name.isEmpty() && !email.isEmpty()) || !uname.isEmpty()) {
                config.config con = new config.config();
                con.ensureUsersTable();
                java.util.List<java.util.Map<String, Object>> rows = con.fetchRecords(
                    "SELECT u_id FROM Users WHERE (u_full_name = ? AND u_email = ?) OR (u_username = ? OR u_email = ?) LIMIT 1",
                    name, email, uname, email
                );
                if (!rows.isEmpty()) {
                    try {
                        currentUserId = Integer.parseInt(String.valueOf(rows.get(0).get("u_id")));
                    } catch (Exception ignore) {}
                }
            }
        }
        if (currentUserId != null) {
            openUserEditor(currentUserId);
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Unable to locate current user.");
        }
    }

    private void openUserEditor(int userId) {
        try {
            ADDuser uform = new ADDuser();
            uform.loadUser(userId);
            uform.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosed(java.awt.event.WindowEvent e) {
                    loadProfile();
                }
            });
            uform.setVisible(true);
        } catch (Throwable ex) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error opening user editor: " + ex.getMessage());
        }
    }

    private void ADD30ActionPerformed(java.awt.event.ActionEvent evt) {
    }

    private void ADD31ActionPerformed(java.awt.event.ActionEvent evt) {
    }

    private void ADD32ActionPerformed(java.awt.event.ActionEvent evt) {
        if ("Admin".equalsIgnoreCase(config.Session.getInstance().getRole())) {
            profileadmin l = new profileadmin();
            l.setVisible(true);
            this.dispose();
        } else {
            profile l = new profile();
            l.setVisible(true);
            this.dispose();
        }
    }

    private void ADD33MouseClicked(java.awt.event.MouseEvent evt) {
        Manage l = new Manage();
        l.setVisible(true);
        this.dispose();
    }

    private void ADD33ActionPerformed(java.awt.event.ActionEvent evt) {
    }

    private void ADD34MouseClicked(java.awt.event.MouseEvent evt) {
        if ("Admin".equalsIgnoreCase(config.Session.getInstance().getRole())) {
            review l = new review();
            l.setVisible(true);
            this.dispose();
        } else {
            homePage2 l = new homePage2();
            l.setVisible(true);
            this.dispose();
        }
    }

    private void ADD34ActionPerformed(java.awt.event.ActionEvent evt) {
        if ("Admin".equalsIgnoreCase(config.Session.getInstance().getRole())) {
            review l = new review();
            l.setVisible(true);
            this.dispose();
        } else {
            homePage2 l = new homePage2();
            l.setVisible(true);
            this.dispose();
        }
    }
    private void ADD35ActionPerformed(java.awt.event.ActionEvent evt) {
               View l = new View();
        l.setVisible(true);
        this.dispose();
    }

    private void ADD36ActionPerformed(java.awt.event.ActionEvent evt) {
        share p = new share();
        p.setVisible(true);
        this.dispose();
    }

    private void ADD37ActionPerformed(java.awt.event.ActionEvent evt) {
        profileadmin p = new profileadmin();
        p.setVisible(true);
        this.dispose();
    }

    private void ADD38MouseClicked(java.awt.event.MouseEvent evt) {
        Manage p = new Manage();
        p.setVisible(true);
        this.dispose();
    }

    private void ADD38ActionPerformed(java.awt.event.ActionEvent evt) {
        Manage p = new Manage();
        p.setVisible(true);
        this.dispose();
    }

    private void ADD39MouseClicked(java.awt.event.MouseEvent evt) {
        homePage2 h = new homePage2();
        h.setVisible(true);
        this.dispose();
    }

    private void ADD39ActionPerformed(java.awt.event.ActionEvent evt) {
        homePage2 p = new homePage2();
        p.setVisible(true);
        this.dispose();
    }

    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(profileadmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(profileadmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(profileadmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(profileadmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                if (config.Session.getInstance().isLoggedIn()) {
                    new profileadmin().setVisible(true);
                } else {
                    new landingPage1().setVisible(true);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ADD28;
    private javax.swing.JButton ADD35;
    private javax.swing.JButton ADD36;
    private javax.swing.JButton ADD37;
    private javax.swing.JButton ADD38;
    private javax.swing.JButton ADD39;
    private javax.swing.JButton EditProfile;
    private javax.swing.JButton EditProfile1;
    private javax.swing.JLabel Followers;
    private javax.swing.JLabel NoRecipes;
    private javax.swing.JButton View;
    private java.awt.Canvas canvas1;
    private java.awt.Choice choice1;
    private javax.swing.JLabel folowers;
    private javax.swing.JLabel folowing;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JDialog jDialog2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JLabel profile;
    private javax.swing.JLabel profileemail1;
    private javax.swing.JLabel profilename1;
    private javax.swing.JTable sharedRecipeOFUser;
    // End of variables declaration//GEN-END:variables
}
