/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dishcovery;
import config.config;
import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public class Update extends javax.swing.JFrame {
    private final config con = new config();

    /**
     * Creates new form homePage2
     */
    public Update() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSpinner1 = new javax.swing.JSpinner();
        jPanel6 = new javax.swing.JPanel();
        jDialog1 = new javax.swing.JDialog();
        choice1 = new java.awt.Choice();
        canvas1 = new java.awt.Canvas();
        jDialog2 = new javax.swing.JDialog();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        ADD3 = new javax.swing.JButton();
        category = new javax.swing.JComboBox<>();
        ADD8 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        ADD9 = new javax.swing.JButton();
        ADD10 = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        ADD7 = new javax.swing.JButton();
        ADD11 = new javax.swing.JButton();
        ADD12 = new javax.swing.JButton();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jPanel15 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        ADD22 = new javax.swing.JButton();
        ADD23 = new javax.swing.JButton();
        ADD24 = new javax.swing.JButton();
        ADD25 = new javax.swing.JButton();
        ADD26 = new javax.swing.JButton();
        ADD27 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();

        jPanel6.setBackground(new java.awt.Color(0, 0, 0,80));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0,80));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 165, 31));
        jLabel1.setText("X");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel1);
        jLabel1.setBounds(840, 0, 20, 30);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 165, 31));
        jLabel4.setText("Dishcovery");
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel4);
        jLabel4.setBounds(20, 0, 100, 30);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 930, 30));
        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 390, -1, -1));

        jPanel2.setLayout(null);

        jPanel12.setBackground(new java.awt.Color(0, 0, 0,50));
        jPanel12.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel12.setLayout(null);

        jTabbedPane1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(null);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 165, 31));
        jLabel9.setText("Update Recipe");
        jPanel3.add(jLabel9);
        jLabel9.setBounds(30, 10, 120, 20);
        jPanel3.add(jTextField1);
        jTextField1.setBounds(10, 60, 160, 20);

        jLabel11.setForeground(new java.awt.Color(255, 165, 31));
        jLabel11.setText("Title");
        jPanel3.add(jLabel11);
        jLabel11.setBounds(10, 40, 60, 20);

        jLabel13.setForeground(new java.awt.Color(255, 165, 31));
        jLabel13.setText("Description");
        jPanel3.add(jLabel13);
        jLabel13.setBounds(10, 100, 70, 20);
        jPanel3.add(jTextField3);
        jTextField3.setBounds(10, 120, 160, 30);
        jPanel3.add(jTextField4);
        jTextField4.setBounds(10, 180, 160, 30);

        jLabel15.setForeground(new java.awt.Color(255, 165, 31));
        jLabel15.setText("Instruction");
        jPanel3.add(jLabel15);
        jLabel15.setBounds(10, 160, 60, 20);

        jLabel16.setForeground(new java.awt.Color(255, 165, 31));
        jLabel16.setText("Date");
        jPanel3.add(jLabel16);
        jLabel16.setBounds(10, 220, 60, 20);
        jPanel3.add(jTextField6);
        jTextField6.setBounds(10, 240, 160, 30);

        jLabel17.setForeground(new java.awt.Color(255, 165, 31));
        jLabel17.setText("Category");
        jPanel3.add(jLabel17);
        jLabel17.setBounds(10, 280, 60, 20);

        ADD3.setBackground(new java.awt.Color(224, 196, 160));
        ADD3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ADD3.setForeground(new java.awt.Color(255, 165, 31));
        ADD3.setText("ADD");
        ADD3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ADD3ActionPerformed(evt);
            }
        });
        jPanel3.add(ADD3);
        ADD3.setBounds(30, 540, 120, 20);

        category.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "appetizers", "salads", "soups", "main dishes", "desserts", "vegetarian", "seasonal" }));
        category.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                categoryActionPerformed(evt);
            }
        });
        jPanel3.add(category);
        category.setBounds(10, 300, 160, 20);

        ADD8.setBackground(new java.awt.Color(224, 196, 160));
        ADD8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ADD8.setForeground(new java.awt.Color(255, 165, 31));
        ADD8.setText("ADD");
        ADD8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ADD8ActionPerformed(evt);
            }
        });
        jPanel3.add(ADD8);
        ADD8.setBounds(40, 340, 100, 30);

        jTabbedPane1.addTab("Recipe", jPanel3);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(null);

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 165, 31));
        jLabel14.setText("ADD Ingredients");
        jPanel4.add(jLabel14);
        jLabel14.setBounds(20, 20, 150, 30);
        jPanel4.add(jTextField2);
        jTextField2.setBounds(10, 90, 160, 20);

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 165, 31));
        jLabel18.setText("Recipe ID");
        jPanel4.add(jLabel18);
        jLabel18.setBounds(10, 70, 60, 20);

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 165, 31));
        jLabel19.setText("name");
        jPanel4.add(jLabel19);
        jLabel19.setBounds(10, 130, 70, 20);
        jPanel4.add(jTextField5);
        jTextField5.setBounds(10, 150, 160, 20);
        jPanel4.add(jTextField7);
        jTextField7.setBounds(10, 210, 160, 20);

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 165, 31));
        jLabel20.setText("Quantity");
        jPanel4.add(jLabel20);
        jLabel20.setBounds(10, 190, 60, 20);

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 165, 31));
        jLabel21.setText("Unit");
        jPanel4.add(jLabel21);
        jLabel21.setBounds(10, 250, 60, 20);
        jPanel4.add(jTextField8);
        jTextField8.setBounds(10, 270, 160, 20);

        ADD9.setBackground(new java.awt.Color(224, 196, 160));
        ADD9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ADD9.setForeground(new java.awt.Color(255, 165, 31));
        ADD9.setText("ADD");
        ADD9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ADD9ActionPerformed(evt);
            }
        });
        jPanel4.add(ADD9);
        ADD9.setBounds(30, 540, 120, 20);

        ADD10.setBackground(new java.awt.Color(224, 196, 160));
        ADD10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ADD10.setForeground(new java.awt.Color(255, 165, 31));
        ADD10.setText("ADD");
        ADD10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ADD10ActionPerformed(evt);
            }
        });
        jPanel4.add(ADD10);
        ADD10.setBounds(40, 310, 100, 30);

        jTabbedPane1.addTab("Ingredients", jPanel4);

        jPanel12.add(jTabbedPane1);
        jTabbedPane1.setBounds(220, 20, 190, 440);

        jPanel8.setBackground(new java.awt.Color(0, 0, 0,80));
        jPanel8.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel8.setLayout(null);

        jLabel22.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 165, 31));
        jLabel22.setText("Manage");
        jLabel22.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel22MouseClicked(evt);
            }
        });
        jPanel8.add(jLabel22);
        jLabel22.setBounds(580, 0, 60, 30);

        ADD7.setBackground(new java.awt.Color(224, 196, 160));
        ADD7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ADD7.setForeground(new java.awt.Color(255, 165, 31));
        ADD7.setText("Delete");
        ADD7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ADD7MouseClicked(evt);
            }
        });
        ADD7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ADD7ActionPerformed(evt);
            }
        });
        jPanel8.add(ADD7);
        ADD7.setBounds(270, 10, 80, 30);

        ADD11.setBackground(new java.awt.Color(224, 196, 160));
        ADD11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ADD11.setForeground(new java.awt.Color(255, 165, 31));
        ADD11.setText("ADD");
        ADD11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ADD11MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ADD11MouseEntered(evt);
            }
        });
        ADD11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ADD11ActionPerformed(evt);
            }
        });
        jPanel8.add(ADD11);
        ADD11.setBounds(30, 10, 80, 30);

        ADD12.setBackground(new java.awt.Color(224, 196, 160));
        ADD12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ADD12.setForeground(new java.awt.Color(255, 165, 31));
        ADD12.setText("Update");
        ADD12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ADD12MouseClicked(evt);
            }
        });
        ADD12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ADD12ActionPerformed(evt);
            }
        });
        jPanel8.add(ADD12);
        ADD12.setBounds(150, 10, 90, 30);

        jPanel12.add(jPanel8);
        jPanel8.setBounds(430, 20, 370, 50);

        jTabbedPane2.setBackground(new java.awt.Color(255, 255, 255));
        jTabbedPane2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jPanel5.setBackground(new java.awt.Color(0, 0, 0,80));
        jPanel5.setLayout(null);

        jTable1.setBackground(new java.awt.Color(0, 0, 0,80));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Recipe ID", "Tittle", "Descrition", "date", "status", "Category"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel5.add(jScrollPane1);
        jScrollPane1.setBounds(0, 0, 390, 350);

        jTabbedPane2.addTab("recipe", jPanel5);

        jTable3.setBackground(new java.awt.Color(0, 0, 0,80));
        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Recipe ID", "Tittle", "Descrition", "date", "status", "Category"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(jTable3);

        jTabbedPane2.addTab("Ingredients", jScrollPane4);

        jPanel12.add(jTabbedPane2);
        jTabbedPane2.setBounds(430, 90, 370, 370);

        jPanel15.setBackground(new java.awt.Color(0, 0, 0,60));
        jPanel15.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel15.setLayout(null);

        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/small logo.png"))); // NOI18N
        jLabel25.setText("jLabel9");
        jPanel15.add(jLabel25);
        jLabel25.setBounds(10, 10, 140, 120);

        ADD22.setBackground(new java.awt.Color(255, 255, 255));
        ADD22.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ADD22.setText("Logout");
        ADD22.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ADD22MouseClicked(evt);
            }
        });
        ADD22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ADD22ActionPerformed(evt);
            }
        });
        jPanel15.add(ADD22);
        ADD22.setBounds(40, 390, 90, 30);

        ADD23.setBackground(new java.awt.Color(255, 255, 255));
        ADD23.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ADD23.setText("Home");
        ADD23.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ADD23MouseClicked(evt);
            }
        });
        ADD23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ADD23ActionPerformed(evt);
            }
        });
        jPanel15.add(ADD23);
        ADD23.setBounds(40, 140, 90, 30);

        ADD24.setBackground(new java.awt.Color(255, 255, 255));
        ADD24.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ADD24.setText("View");
        ADD24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ADD24ActionPerformed(evt);
            }
        });
        jPanel15.add(ADD24);
        ADD24.setBounds(40, 240, 90, 30);

        ADD25.setBackground(new java.awt.Color(255, 255, 255));
        ADD25.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ADD25.setText("Share");
        ADD25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ADD25ActionPerformed(evt);
            }
        });
        jPanel15.add(ADD25);
        ADD25.setBounds(40, 290, 90, 30);

        ADD26.setBackground(new java.awt.Color(255, 255, 255));
        ADD26.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ADD26.setText("Profile");
        ADD26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ADD26ActionPerformed(evt);
            }
        });
        jPanel15.add(ADD26);
        ADD26.setBounds(40, 340, 90, 30);

        ADD27.setBackground(new java.awt.Color(255, 255, 255));
        ADD27.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ADD27.setText("Manage");
        ADD27.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ADD27MouseClicked(evt);
            }
        });
        ADD27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ADD27ActionPerformed(evt);
            }
        });
        jPanel15.add(ADD27);
        ADD27.setBounds(40, 190, 90, 30);

        jPanel12.add(jPanel15);
        jPanel15.setBounds(20, 20, 180, 440);

        jPanel2.add(jPanel12);
        jPanel12.setBounds(20, 60, 840, 480);

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/new back.png"))); // NOI18N
        jLabel12.setText("jLabel12");
        jPanel2.add(jLabel12);
        jLabel12.setBounds(0, 0, 880, 580);

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 930, 570));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ADD3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ADD3ActionPerformed
        String title = jTextField1.getText().trim();
        String desc = jTextField3.getText().trim();
        String author = String.valueOf(category.getSelectedItem());
        if (title.isEmpty() || desc.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Title and Description are required");
            return;
        }
        con.addRecord("INSERT INTO Recipes (r_title, r_description, r_author) VALUES (?, ?, ?)", title, desc, author);
        JOptionPane.showMessageDialog(this, "Recipe added");
    }//GEN-LAST:event_ADD3ActionPerformed

    private void categoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_categoryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_categoryActionPerformed

    private void ADD8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ADD8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ADD8ActionPerformed

    private void ADD9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ADD9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ADD9ActionPerformed

    private void ADD10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ADD10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ADD10ActionPerformed

    private void jLabel22MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel22MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel22MouseClicked

    private void ADD7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ADD7MouseClicked
        Delete l = new Delete();
        l.setVisible(true);
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_ADD7MouseClicked

    private void ADD7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ADD7ActionPerformed
        String title = jTextField1.getText().trim();
        String desc = jTextField3.getText().trim();
        String author = String.valueOf(category.getSelectedItem());
        if (title.isEmpty() || desc.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Title and Description are required");
            return;
        }
        con.addRecord("INSERT INTO Recipes (r_title, r_description, r_author) VALUES (?, ?, ?)", title, desc, author);
        JOptionPane.showMessageDialog(this, "Recipe added");
    }//GEN-LAST:event_ADD7ActionPerformed

    private void ADD11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ADD11MouseClicked
        Manage l = new Manage();
        l.setVisible(true);
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_ADD11MouseClicked

    private void ADD11MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ADD11MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_ADD11MouseEntered

    private void ADD11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ADD11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ADD11ActionPerformed

    private void ADD12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ADD12MouseClicked
        Update l = new Update();
        l.setVisible(true);
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_ADD12MouseClicked

    private void ADD12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ADD12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ADD12ActionPerformed

    private void ADD22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ADD22ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ADD22ActionPerformed

    private void ADD23MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ADD23MouseClicked
        homePage2 l = new homePage2();
        l.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ADD23MouseClicked

    private void ADD23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ADD23ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ADD23ActionPerformed

    private void ADD24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ADD24ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ADD24ActionPerformed

    private void ADD25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ADD25ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ADD25ActionPerformed

    private void ADD26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ADD26ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ADD26ActionPerformed

    private void ADD27MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ADD27MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_ADD27MouseClicked

    private void ADD27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ADD27ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ADD27ActionPerformed

    private void ADD22MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ADD22MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_ADD22MouseClicked
    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) { }
    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) { }
    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) { }
    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) { }
    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) { }
    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) { }
    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) { }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Update().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ADD10;
    private javax.swing.JButton ADD11;
    private javax.swing.JButton ADD12;
    private javax.swing.JButton ADD22;
    private javax.swing.JButton ADD23;
    private javax.swing.JButton ADD24;
    private javax.swing.JButton ADD25;
    private javax.swing.JButton ADD26;
    private javax.swing.JButton ADD27;
    private javax.swing.JButton ADD3;
    private javax.swing.JButton ADD7;
    private javax.swing.JButton ADD8;
    private javax.swing.JButton ADD9;
    private java.awt.Canvas canvas1;
    private javax.swing.JComboBox<String> category;
    private java.awt.Choice choice1;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JDialog jDialog2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    // End of variables declaration//GEN-END:variables
}
