/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dishcovery;
import config.config;

/**
 *
 * @author user
 */
public class View extends javax.swing.JFrame {
    private final config con = new config();
    public static String initialSearchText = null;
    public static String initialCategory = null;

    /**
     * Creates new form homePage2
     */
    public View() {
        initComponents();
        applyInitialFiltersAndDisplay();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSpinner1 = new javax.swing.JSpinner();
        jPanel6 = new javax.swing.JPanel();
        jDialog1 = new javax.swing.JDialog();
        choice1 = new java.awt.Choice();
        canvas1 = new java.awt.Canvas();
        jDialog2 = new javax.swing.JDialog();
        jScrollPane3 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        Search = new javax.swing.JTextField();
        ADD7 = new javax.swing.JButton();
        category = new javax.swing.JComboBox<>();
        ADD10 = new javax.swing.JButton();
        Myrecipes = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        myrecipes = new javax.swing.JTable();
        jPanel16 = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        ADD30 = new javax.swing.JButton();
        ADD31 = new javax.swing.JButton();
        ADD32 = new javax.swing.JButton();
        ADD33 = new javax.swing.JButton();
        ADD34 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();

        jPanel6.setBackground(new java.awt.Color(0, 0, 0,80));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 390, -1, -1));

        jPanel2.setLayout(null);

        jPanel8.setBackground(new java.awt.Color(0, 0, 0,50));
        jPanel8.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel8.setLayout(null);

        jPanel7.setBackground(new java.awt.Color(0, 0, 0,60));
        jPanel7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel7.setLayout(null);

        Search.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        Search.setText("Search my recipes by name or ID");
        Search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchActionPerformed(evt);
            }
        });
        jPanel7.add(Search);
        Search.setBounds(10, 10, 270, 30);

        ADD7.setBackground(new java.awt.Color(255, 255, 255));
        ADD7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ADD7.setText("Refresh");
        ADD7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ADD7ActionPerformed(evt);
            }
        });
        jPanel7.add(ADD7);
        ADD7.setBounds(380, 10, 83, 30);

        category.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "appetizers", "salads", "soups", "main dishes", "desserts", "vegetarian", "seasonal" }));
        category.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                categoryActionPerformed(evt);
            }
        });
        jPanel7.add(category);
        category.setBounds(490, 10, 90, 20);

        ADD10.setBackground(new java.awt.Color(255, 255, 255));
        ADD10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ADD10.setText("Search");
        ADD10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ADD10ActionPerformed(evt);
            }
        });
        jPanel7.add(ADD10);
        ADD10.setBounds(290, 10, 80, 30);

        jPanel8.add(jPanel7);
        jPanel7.setBounds(230, 20, 590, 50);

        Myrecipes.setBackground(new java.awt.Color(0, 0, 0,60));
        Myrecipes.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Myrecipes.setLayout(null);

        myrecipes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(myrecipes);

        Myrecipes.add(jScrollPane1);
        jScrollPane1.setBounds(0, 0, 590, 420);

        jPanel8.add(Myrecipes);
        Myrecipes.setBounds(230, 70, 590, 420);

        jPanel16.setBackground(new java.awt.Color(0, 0, 0,60));
        jPanel16.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel16.setLayout(null);

        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/small logo.png"))); // NOI18N
        jLabel27.setText("jLabel9");
        jPanel16.add(jLabel27);
        jLabel27.setBounds(10, 10, 140, 120);

        ADD30.setBackground(new java.awt.Color(255, 255, 255));
        ADD30.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ADD30.setText("View");
        ADD30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ADD30ActionPerformed(evt);
            }
        });
        jPanel16.add(ADD30);
        ADD30.setBounds(40, 270, 90, 30);

        ADD31.setBackground(new java.awt.Color(255, 255, 255));
        ADD31.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ADD31.setText("Share");
        ADD31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ADD31ActionPerformed(evt);
            }
        });
        jPanel16.add(ADD31);
        ADD31.setBounds(40, 320, 90, 30);

        ADD32.setBackground(new java.awt.Color(255, 255, 255));
        ADD32.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ADD32.setText("Profile");
        ADD32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ADD32ActionPerformed(evt);
            }
        });
        jPanel16.add(ADD32);
        ADD32.setBounds(40, 370, 90, 30);

        ADD33.setBackground(new java.awt.Color(255, 255, 255));
        ADD33.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ADD33.setText("Manage");
        ADD33.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ADD33MouseClicked(evt);
            }
        });
        ADD33.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ADD33ActionPerformed(evt);
            }
        });
        jPanel16.add(ADD33);
        ADD33.setBounds(40, 220, 90, 30);

        ADD34.setBackground(new java.awt.Color(255, 255, 255));
        ADD34.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ADD34.setText("Home");
        ADD34.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ADD34MouseClicked(evt);
            }
        });
        ADD34.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ADD34ActionPerformed(evt);
            }
        });
        jPanel16.add(ADD34);
        ADD34.setBounds(40, 170, 90, 30);

        jPanel8.add(jPanel16);
        jPanel16.setBounds(20, 20, 180, 470);

        jPanel2.add(jPanel8);
        jPanel8.setBounds(20, 30, 840, 510);

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/new back.png"))); // NOI18N
        jLabel12.setText("jLabel12");
        jPanel2.add(jLabel12);
        jLabel12.setBounds(0, -10, 880, 590);

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 880, 570));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ADD7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ADD7ActionPerformed
        Search.setText("");
        if (category.getItemCount() > 0) {
            category.setSelectedIndex(0);
        }
        displayMyRecipes(null, null);
    }//GEN-LAST:event_ADD7ActionPerformed

    private void categoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_categoryActionPerformed
        String cat = category.getSelectedItem() != null ? category.getSelectedItem().toString() : null;
        String txt = Search.getText() != null ? Search.getText().trim() : null;
        displayMyRecipes(txt, cat);
    }//GEN-LAST:event_categoryActionPerformed

    private void SearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchActionPerformed
        ADD10ActionPerformed(null);
    }//GEN-LAST:event_SearchActionPerformed

    private void ADD10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ADD10ActionPerformed
        String txt = Search.getText() != null ? Search.getText().trim() : null;
        String cat = category.getSelectedItem() != null ? category.getSelectedItem().toString() : null;
        displayMyRecipes(txt, cat);
    }//GEN-LAST:event_ADD10ActionPerformed

    private void ADD30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ADD30ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ADD30ActionPerformed

    private void ADD31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ADD31ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ADD31ActionPerformed

    private void ADD32ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ADD32ActionPerformed
        profile l = new profile();
        l.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ADD32ActionPerformed

    private void ADD33MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ADD33MouseClicked
        Manage l = new Manage();
        l.setVisible(true);
        this.dispose();         // TODO add your handling code here:
    }//GEN-LAST:event_ADD33MouseClicked

    private void ADD33ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ADD33ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ADD33ActionPerformed

    private void ADD34MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ADD34MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_ADD34MouseClicked

    private void ADD34ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ADD34ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ADD34ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new View().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ADD10;
    private javax.swing.JButton ADD30;
    private javax.swing.JButton ADD31;
    private javax.swing.JButton ADD32;
    private javax.swing.JButton ADD33;
    private javax.swing.JButton ADD34;
    private javax.swing.JButton ADD7;
    private javax.swing.JPanel Myrecipes;
    private javax.swing.JTextField Search;
    private java.awt.Canvas canvas1;
    private javax.swing.JComboBox<String> category;
    private java.awt.Choice choice1;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JDialog jDialog2;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JTable myrecipes;
    // End of variables declaration//GEN-END:variables

    private void applyInitialFiltersAndDisplay() {
        String txt = initialSearchText;
        String cat = initialCategory;
        initialSearchText = null;
        initialCategory = null;
        displayMyRecipes(txt, cat);
    }

    private void displayMyRecipes(String searchTxt, String categoryFilter) {
        String author = login.currentUserIdentifier != null ? login.currentUserIdentifier : "";
        StringBuilder sql = new StringBuilder("SELECT r_id AS ID, r_title AS Title, r_category AS Category, r_date AS Date FROM Recipes WHERE r_author = ?");
        java.util.List<Object> params = new java.util.ArrayList<>();
        params.add(author);
        if (searchTxt != null && !searchTxt.trim().isEmpty()) {
            sql.append(" AND (r_title LIKE ? OR CAST(r_id AS TEXT) LIKE ?)");
            params.add("%" + searchTxt.trim() + "%");
            params.add("%" + searchTxt.trim() + "%");
        }
        if (categoryFilter != null && !categoryFilter.trim().isEmpty()) {
            sql.append(" AND r_category = ?");
            params.add(categoryFilter.trim());
        }
        con.displayData(sql.toString(), myrecipes, params.toArray());
    }
}
